module.exports = {
  units: [
    // ---------------- EFFECTIVE DART ----------------
    {
      number: "x",
      title: "Effective Dart — Style & Conventions",
      blocks: [
        { type: "p", text: "Dart's official style guide (\"Effective Dart\") is unusually well-followed across the ecosystem, which makes any Dart/Flutter codebase you open feel familiar. The `dart format` tool enforces most formatting automatically; the conventions below are the ones a formatter cannot decide for you." },
        { type: "h3", text: "Naming Conventions" },
        { type: "table", header: ["Element", "Convention", "Example"],
          rows: [
            ["Classes, enums, extensions, typedefs", "UpperCamelCase", "`class StudentCard`, `enum Status`"],
            ["Variables, functions, parameters", "lowerCamelCase", "`int rollNumber`, `void fetchData()`"],
            ["Constants", "lowerCamelCase (not SCREAMING_CASE)", "`const pi = 3.14159;`"],
            ["Files and folders", "lowercase_with_underscores", "`student_card.dart`"],
            ["Private members", "Prefix with a single underscore", "`int _count;`, `class _MyWidgetState`"],
          ]},
        { type: "h3", text: "Formatting & Linting" },
        { type: "code", text: [
          "# Auto-format every Dart file in the project",
          "dart format .",
          "",
          "# Run the static analyzer for type errors, unused imports, and lint issues",
          "dart analyze",
        ].join("\n") },
        { type: "p", text: "Most Flutter projects also include an `analysis_options.yaml` file that pulls in the community-standard `flutter_lints` package, which adds recommended lint rules on top of the base analyzer." },
        { type: "code", text: [
          "# analysis_options.yaml",
          "include: package:flutter_lints/flutter.yaml",
          "",
          "linter:",
          "  rules:",
          "    prefer_const_constructors: true",
          "    avoid_print: true",
        ].join("\n") },
        { type: "h3", text: "Practical Guidelines" },
        { type: "ul", items: [
          "Prefer `final` over `var` for any variable that is assigned exactly once — it communicates intent and prevents accidental reassignment.",
          "Use `const` constructors wherever the widget's configuration is genuinely fixed at compile time (see Unit 27's performance discussion for why this matters, not just style).",
          "Keep one class per file where reasonable, and name the file after the class it contains.",
          "Write doc comments (`///`) on public APIs — they show up in IDE tooltips and generated documentation.",
        ]},
        { type: "code", text: [
          "/// Represents a single student enrolled in the department.",
          "///",
          "/// [rollNumber] must be unique within an academic year.",
          "class Student {",
          "  final String name;",
          "  final int rollNumber;",
          "  const Student({required this.name, required this.rollNumber});",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "`dart format` and `dart analyze` should run cleanly before every commit — most teams enforce this in CI.",
          "Naming conventions (UpperCamelCase for types, lowerCamelCase for members) are followed almost universally across the Dart ecosystem.",
          "`///` doc comments are worth writing on anything public — they're not just documentation, they power IDE autocomplete tooltips.",
        ]},
      ],
    },

    // ---------------- ITERABLES DEEP DIVE ----------------
    {
      number: "x",
      title: "Iterables — A Functional Programming Deep Dive",
      blocks: [
        { type: "p", text: "Unit 4 introduced `where`, `map`, and `reduce`. Dart's `Iterable` interface (implemented by `List`, `Set`, and more) offers a much richer functional toolkit that, once familiar, replaces the majority of manual loops you'd otherwise write." },
        { type: "table", header: ["Method", "Returns", "Purpose"],
          rows: [
            ["`map(f)`", "`Iterable`", "Transform every element"],
            ["`where(f)`", "`Iterable`", "Keep only elements matching a condition"],
            ["`fold(initial, f)`", "A single value", "Accumulate a result across all elements, with a starting value"],
            ["`reduce(f)`", "A single value", "Like `fold`, but uses the first element as the starting value (fails on empty)"],
            ["`expand(f)`", "`Iterable`", "Map each element to zero or more results and flatten them"],
            ["`take(n)` / `skip(n)`", "`Iterable`", "First `n` elements / all but the first `n`"],
            ["`takeWhile(f)` / `skipWhile(f)`", "`Iterable`", "Elements while a condition holds, from the start"],
            ["`firstWhere(f)`", "A single element", "First element matching a condition (throws if none found — use `orElse`)"],
            ["`every(f)` / `any(f)`", "`bool`", "True if all / any elements satisfy the condition"],
            ["`toList()` / `toSet()`", "`List` / `Set`", "Materialize a lazy iterable into a concrete collection"],
          ]},
        { type: "code", text: [
          "List<Map<String, dynamic>> students = [",
          "  {'name': 'Anita', 'marks': 92},",
          "  {'name': 'Ravi', 'marks': 58},",
          "  {'name': 'Priya', 'marks': 76},",
          "];",
          "",
          "// fold — compute the average marks",
          "double average = students.fold(0, (sum, s) => sum + (s['marks'] as int)) / students.length;",
          "print(average); // 75.33...",
          "",
          "// where + map chained — names of students who passed with distinction",
          "var distinctionNames = students",
          "    .where((s) => (s['marks'] as int) >= 75)",
          "    .map((s) => s['name'])",
          "    .toList();",
          "print(distinctionNames); // [Anita, Priya]",
          "",
          "// expand — flatten a list of lists",
          "var nested = [[1, 2], [3, 4], [5]];",
          "var flat = nested.expand((list) => list).toList();",
          "print(flat); // [1, 2, 3, 4, 5]",
          "",
          "// firstWhere with a fallback",
          "var topper = students.firstWhere(",
          "  (s) => (s['marks'] as int) > 90,",
          "  orElse: () => {'name': 'None', 'marks': 0},",
          ");",
          "print(topper['name']); // Anita",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`Iterable` operations are **lazy** by default — chaining `.where().map()` does not actually iterate the collection until something forces evaluation, like `.toList()`, `.length`, or a `for-in` loop. This means you can chain several transformations without worrying about intermediate copies being built at each step." },
        { type: "keypoints", items: [
          "`fold` and `reduce` both accumulate a single result; `fold` lets you specify a starting value, `reduce` does not.",
          "`expand` flattens one level of nesting while mapping — useful for turning a list of lists into a single list.",
          "Iterable chains are lazy; nothing actually runs until you call something that forces evaluation.",
        ]},
      ],
    },

    // ---------------- DATETIME ----------------
    {
      number: "x",
      title: "Working with DateTime & Duration",
      blocks: [
        { type: "h3", text: "Creating and Reading Dates" },
        { type: "code", text: [
          "DateTime now = DateTime.now();",
          "DateTime specific = DateTime(2026, 7, 6);           // July 6, 2026",
          "DateTime parsed = DateTime.parse('2026-07-06T10:30:00');",
          "",
          "print(now.year);",
          "print(now.month);",
          "print(now.weekday); // 1 = Monday ... 7 = Sunday",
        ].join("\n") },
        { type: "h3", text: "Duration & Date Arithmetic" },
        { type: "code", text: [
          "DateTime deadline = DateTime.now().add(const Duration(days: 7));",
          "DateTime pastEvent = DateTime.now().subtract(const Duration(hours: 3));",
          "",
          "Duration difference = deadline.difference(DateTime.now());",
          "print('${difference.inDays} days remaining');",
          "",
          "bool isOverdue = DateTime.now().isAfter(deadline);",
        ].join("\n") },
        { type: "h3", text: "Formatting with intl" },
        { type: "code", text: [
          "import 'package:intl/intl.dart';",
          "",
          "final formatted = DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now());",
          "print(formatted); // e.g. 06 Jul 2026, 03:45 PM",
        ].join("\n") },
        { type: "note", kind: "warning", text: "`DateTime.now()` returns the device's local time by default. When storing timestamps that need to be compared across time zones (e.g. a server-side deadline), convert explicitly with `.toUtc()` before storing, and `.toLocal()` only when displaying to the user." },
        { type: "keypoints", items: [
          "`DateTime` represents a specific point in time; `Duration` represents a span of time.",
          "`.add()`/`.subtract()` with a `Duration` is the correct way to shift a date, rather than manual day/month arithmetic.",
          "Store timestamps in UTC and convert to local time only for display, to avoid time-zone bugs.",
        ]},
      ],
    },
  ],
};
