module.exports = {
  units: [
    // ---------------- EXTENSION METHODS ----------------
    {
      number: "x",
      title: "Extension Methods",
      blocks: [
        { type: "p", text: "Extension methods let you add new functionality to an **existing** type — including types you don't own, like `String` or `int` from the Dart core library — without subclassing it or modifying its source. This is purely a compile-time, syntactic convenience; it does not change the underlying class." },
        { type: "h3", text: "Defining and Using an Extension" },
        { type: "code", text: [
          "extension StringValidation on String {",
          "  bool get isValidEmail => contains('@') && contains('.');",
          "",
          "  String capitalize() {",
          "    if (isEmpty) return this;",
          "    return this[0].toUpperCase() + substring(1);",
          "  }",
          "}",
          "",
          "void main() {",
          "  print('sudhakar@lbrce.ac.in'.isValidEmail); // true",
          "  print('flutter'.capitalize());              // Flutter",
          "}",
        ].join("\n") },
        { type: "h3", text: "Extensions on Custom and Generic Types" },
        { type: "code", text: [
          "extension ListSum on List<int> {",
          "  int get total => fold(0, (sum, item) => sum + item);",
          "}",
          "",
          "void main() {",
          "  print([10, 20, 30].total); // 60",
          "}",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Extension methods are resolved statically, based on the variable's declared type at the call site — not its runtime type. If two imported extensions define the same member name for the same type, you'll need to disambiguate with an explicit `import 'package:x.dart' show ExtensionName` or by calling `ExtensionName(value).member`." },
        { type: "keypoints", items: [
          "Extensions add methods/getters to existing types without inheritance or modifying the original source.",
          "They are resolved at compile time based on static type, not the runtime object's actual type.",
          "Widely used in Flutter codebases for small conveniences, e.g. `context.theme`, `.toDateString()` on `DateTime`.",
        ]},
      ],
    },

    // ---------------- RECORDS & PATTERNS ----------------
    {
      number: "x",
      title: "Records & Pattern Matching (Dart 3)",
      blocks: [
        { type: "p", text: "Dart 3 introduced two closely related features that significantly reduce boilerplate: **records**, a way to bundle multiple values together without declaring a class, and **pattern matching**, a way to inspect and destructure data in a single, declarative expression." },
        { type: "h3", text: "Records" },
        { type: "code", text: [
          "// A record with positional fields",
          "(String, int) getStudent() {",
          "  return ('Anita', 101);",
          "}",
          "",
          "// A record with named fields — often clearer",
          "({String name, int rollNumber}) getStudentNamed() {",
          "  return (name: 'Anita', rollNumber: 101);",
          "}",
          "",
          "void main() {",
          "  var (name, roll) = getStudent();     // destructuring assignment",
          "  print('$name: $roll');",
          "",
          "  var student = getStudentNamed();",
          "  print('${student.name}: ${student.rollNumber}');",
          "}",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Records are the idiomatic replacement for returning multiple values from a function — previously you'd need a small custom class or an untyped `List`/`Map` just to return a pair of values." },
        { type: "h3", text: "Pattern Matching with switch" },
        { type: "code", text: [
          "String describe(Object value) {",
          "  return switch (value) {",
          "    int n when n < 0 => 'Negative number',",
          "    int n when n == 0 => 'Zero',",
          "    int() => 'Positive number',",
          "    String s => 'A string of length ${s.length}',",
          "    [int a, int b] => 'A pair: $a, $b',",
          "    _ => 'Unknown type',",
          "  };",
          "}",
          "",
          "void main() {",
          "  print(describe(-5));       // Negative number",
          "  print(describe('hi'));     // A string of length 2",
          "  print(describe([1, 2]));   // A pair: 1, 2",
          "}",
        ].join("\n") },
        { type: "h3", text: "Destructuring in Practice" },
        { type: "code", text: [
          "Map<String, dynamic> json = {'name': 'Ravi', 'age': 21};",
          "",
          "// Destructure a map directly in a variable declaration",
          "var {'name': String name, 'age': int age} = json;",
          "print('$name is $age');",
        ].join("\n") },
        { type: "keypoints", items: [
          "Records (`(...)` or `(field: value, ...)`) bundle multiple values without needing a dedicated class.",
          "Pattern matching in `switch` expressions can match on type, structure, and conditions (`when`) in one place.",
          "Destructuring assignment pulls values straight out of records, lists, and maps into named variables.",
        ]},
      ],
    },

    // ---------------- ISOLATES ----------------
    {
      number: "x",
      title: "Isolates & Concurrency",
      blocks: [
        { type: "p", text: "Dart code runs on a single thread by default, using an event loop to interleave asynchronous work (this is what `Future`/`async`/`await` manage). For genuinely **CPU-intensive** work — parsing a huge JSON file, image processing, complex calculations — that would otherwise block the UI thread and cause visible jank, Dart provides **isolates**: independent workers with their own memory, running in true parallel." },
        { type: "h3", text: "Why Not Just Use a Future?" },
        { type: "p", text: "A `Future` schedules work to run *later* on the same single thread — it does not run in parallel, and a long, synchronous, CPU-bound loop inside an `async` function will still freeze the UI, because the event loop can't process anything else until that loop finishes. Isolates solve this by running the heavy work on a genuinely separate thread." },
        { type: "h3", text: "compute() — the simple way in Flutter" },
        { type: "p", text: "Flutter's `compute()` function wraps isolate creation for the common case: run one function, with one argument, on a background isolate, and get the result back as a `Future`." },
        { type: "code", text: [
          "import 'package:flutter/foundation.dart';",
          "",
          "// This function must be a top-level or static function",
          "int expensiveCalculation(int input) {",
          "  int result = 0;",
          "  for (int i = 0; i < 1000000000; i++) {",
          "    result += i % input;",
          "  }",
          "  return result;",
          "}",
          "",
          "Future<void> runInBackground() async {",
          "  final result = await compute(expensiveCalculation, 7);",
          "  print('Result: $result');",
          "}",
        ].join("\n") },
        { type: "h3", text: "Manual Isolates with Isolate.spawn" },
        { type: "code", text: [
          "import 'dart:isolate';",
          "",
          "void heavyWork(SendPort sendPort) {",
          "  int sum = 0;",
          "  for (int i = 0; i < 1000000000; i++) {",
          "    sum += i;",
          "  }",
          "  sendPort.send(sum);",
          "}",
          "",
          "Future<void> main() async {",
          "  final receivePort = ReceivePort();",
          "  await Isolate.spawn(heavyWork, receivePort.sendPort);",
          "  final result = await receivePort.first;",
          "  print('Sum: $result');",
          "}",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Isolates do not share memory — data passed between them is copied, not referenced. This means you cannot pass things like an open database connection or a `BuildContext` into an isolate; only simple, serializable data (numbers, strings, lists, maps of those) can cross the boundary safely." },
        { type: "keypoints", items: [
          "Dart's event loop handles asynchronous *waiting* (Futures) on a single thread; it does not give you true parallelism.",
          "Isolates run on separate threads with their own memory, ideal for genuinely CPU-heavy work.",
          "`compute()` is the easiest entry point for one-off background computation in a Flutter app.",
        ]},
      ],
    },
  ],
};
