module.exports = {
  units: [
    // ---------------- APP LIFECYCLE ----------------
    {
      number: "x",
      title: "App Lifecycle & State Restoration",
      blocks: [
        { type: "p", text: "A mobile app moves through several lifecycle states as the user switches apps, locks the phone, or the OS reclaims memory. Reacting correctly — pausing a video, saving a draft, disconnecting a stream — prevents wasted resources and, at worst, data loss." },
        { type: "h3", text: "Observing Lifecycle Changes" },
        { type: "code", text: [
          "class LifecycleAwareScreen extends StatefulWidget {",
          "  const LifecycleAwareScreen({super.key});",
          "  @override",
          "  State<LifecycleAwareScreen> createState() => _LifecycleAwareScreenState();",
          "}",
          "",
          "class _LifecycleAwareScreenState extends State<LifecycleAwareScreen>",
          "    with WidgetsBindingObserver {",
          "  @override",
          "  void initState() {",
          "    super.initState();",
          "    WidgetsBinding.instance.addObserver(this);",
          "  }",
          "",
          "  @override",
          "  void dispose() {",
          "    WidgetsBinding.instance.removeObserver(this);",
          "    super.dispose();",
          "  }",
          "",
          "  @override",
          "  void didChangeAppLifecycleState(AppLifecycleState state) {",
          "    if (state == AppLifecycleState.paused) {",
          "      print('App moved to background — save draft state here');",
          "    } else if (state == AppLifecycleState.resumed) {",
          "      print('App back in foreground — refresh data if needed');",
          "    }",
          "  }",
          "",
          "  @override",
          "  Widget build(BuildContext context) => const SizedBox();",
          "}",
        ].join("\n") },
        { type: "table", header: ["State", "Meaning"],
          rows: [
            ["`resumed`", "App is visible and responding to user input"],
            ["`inactive`", "App is in the foreground but not receiving input (e.g. an incoming call overlay)"],
            ["`paused`", "App is not visible — moved to the background"],
            ["`detached`", "App is still hosted by Flutter but detached from any view (rare, mostly during teardown)"],
          ]},
        { type: "keypoints", items: [
          "`WidgetsBindingObserver` + `didChangeAppLifecycleState` is how a widget reacts to the app moving to background/foreground.",
          "`paused` is the natural place to persist unsaved work; `resumed` is a natural place to refresh stale data.",
          "Always remove the observer in `dispose()`, mirroring the pairing rule from other lifecycle-bound resources (Unit 15, Unit 23).",
        ]},
      ],
    },

    // ---------------- ERROR HANDLING & CRASH REPORTING ----------------
    {
      number: "x",
      title: "Error Handling & Crash Reporting in Production",
      blocks: [
        { type: "p", text: "A shipped app needs a strategy for errors beyond a local `try`/`catch` — both to avoid a blank, crashed screen for the user, and to actually find out an error happened at all once the app is in someone else's hands." },
        { type: "h3", text: "Catching Flutter Framework Errors" },
        { type: "code", text: [
          "void main() {",
          "  FlutterError.onError = (FlutterErrorDetails details) {",
          "    // Log to console during development",
          "    FlutterError.presentError(details);",
          "    // In production, forward to a crash-reporting service instead/also:",
          "    // FirebaseCrashlytics.instance.recordFlutterFatalError(details);",
          "  };",
          "  runApp(const MyApp());",
          "}",
        ].join("\n") },
        { type: "h3", text: "Catching Everything Else with runZonedGuarded" },
        { type: "p", text: "`FlutterError.onError` only covers errors thrown during widget building/layout/painting. Errors in your own async code (a background `Future`, an uncaught exception in a callback) need a Zone-level guard to be caught centrally." },
        { type: "code", text: [
          "import 'dart:async';",
          "",
          "void main() {",
          "  runZonedGuarded(() {",
          "    runApp(const MyApp());",
          "  }, (error, stackTrace) {",
          "    print('Uncaught error: $error');",
          "    // FirebaseCrashlytics.instance.recordError(error, stackTrace);",
          "  });",
          "}",
        ].join("\n") },
        { type: "h3", text: "A User-Friendly Fallback UI" },
        { type: "code", text: [
          "ErrorWidget.builder = (FlutterErrorDetails details) {",
          "  return Scaffold(",
          "    body: Center(",
          "      child: Text('Something went wrong. Please restart the app.'),",
          "    ),",
          "  );",
          "};",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`firebase_crashlytics` and `sentry_flutter` are the two most widely used crash-reporting services in the Flutter ecosystem — both provide drop-in hooks for exactly the two handlers shown above, plus a dashboard of every crash, its stack trace, and how many users it affected." },
        { type: "keypoints", items: [
          "`FlutterError.onError` catches framework-level errors (build/layout/paint); `runZonedGuarded` catches everything else, including async errors.",
          "`ErrorWidget.builder` replaces Flutter's default red error screen with something presentable to end users.",
          "A crash-reporting service (Crashlytics, Sentry) is what turns \"a user's app is crashing somewhere\" into an actionable, specific bug report.",
        ]},
      ],
    },

    // ---------------- CAMERA & MEDIA ----------------
    {
      number: "x",
      title: "Working with Camera, Gallery & Media",
      blocks: [
        { type: "p", text: "The `image_picker` package covers the overwhelming majority of apps' media needs — capturing a photo, recording video, or picking existing media from the gallery — through one simple, cross-platform API." },
        { type: "code", text: [
          "import 'package:image_picker/image_picker.dart';",
          "",
          "final ImagePicker _picker = ImagePicker();",
          "",
          "Future<void> pickFromGallery() async {",
          "  final XFile? image = await _picker.pickImage(source: ImageSource.gallery);",
          "  if (image != null) {",
          "    print('Picked: ${image.path}');",
          "  }",
          "}",
          "",
          "Future<void> takePhoto() async {",
          "  final XFile? photo = await _picker.pickImage(",
          "    source: ImageSource.camera,",
          "    maxWidth: 1200,",
          "    imageQuality: 85,",
          "  );",
          "  if (photo != null) {",
          "    print('Captured: ${photo.path}');",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Displaying the Picked Image" },
        { type: "code", text: [
          "import 'dart:io';",
          "",
          "Image.file(File(image.path))",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Camera and gallery access require platform-specific permission declarations — `NSCameraUsageDescription`/`NSPhotoLibraryUsageDescription` in iOS's `Info.plist`, and the `CAMERA` permission in Android's manifest — plus a runtime permission request via a package like `permission_handler` on Android 6.0+ and iOS." },
        { type: "keypoints", items: [
          "`image_picker` handles both camera capture and gallery selection through one unified API returning an `XFile`.",
          "`maxWidth`/`imageQuality` let you downscale/compress an image at pick time, avoiding unnecessarily large uploads later.",
          "Camera/gallery access always requires explicit platform permission declarations, not just a Dart-side package.",
        ]},
      ],
    },

    // ---------------- GEOLOCATION ----------------
    {
      number: "x",
      title: "Geolocation & Maps Overview",
      blocks: [
        { type: "p", text: "The `geolocator` package is the standard way to read a device's GPS location; `google_maps_flutter` (or `flutter_map` for an open-source, non-Google alternative) renders an interactive map." },
        { type: "h3", text: "Getting the Current Location" },
        { type: "code", text: [
          "import 'package:geolocator/geolocator.dart';",
          "",
          "Future<Position> getCurrentLocation() async {",
          "  LocationPermission permission = await Geolocator.checkPermission();",
          "  if (permission == LocationPermission.denied) {",
          "    permission = await Geolocator.requestPermission();",
          "  }",
          "",
          "  return Geolocator.getCurrentPosition(",
          "    desiredAccuracy: LocationAccuracy.high,",
          "  );",
          "}",
        ].join("\n") },
        { type: "h3", text: "Displaying a Map" },
        { type: "code", text: [
          "import 'package:google_maps_flutter/google_maps_flutter.dart';",
          "",
          "GoogleMap(",
          "  initialCameraPosition: const CameraPosition(",
          "    target: LatLng(16.4419, 80.6183), // Mylavaram, Andhra Pradesh",
          "    zoom: 14,",
          "  ),",
          "  markers: {",
          "    const Marker(",
          "      markerId: MarkerId('college'),",
          "      position: LatLng(16.4419, 80.6183),",
          "      infoWindow: InfoWindow(title: 'LBRCE'),",
          "    ),",
          "  },",
          ")",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`google_maps_flutter` requires an API key configured natively for both Android (`AndroidManifest.xml`) and iOS (`AppDelegate.swift`) — this is a native platform setup step, not something Dart code alone can configure." },
        { type: "keypoints", items: [
          "Always check and, if needed, request location permission before calling `getCurrentPosition()` — it throws if permission was never granted.",
          "`google_maps_flutter` needs a valid, natively-configured Google Maps API key per platform before it will render anything.",
          "`flutter_map` is a common Google-Maps-free alternative when avoiding Google API keys/billing is a requirement.",
        ]},
      ],
    },

    // ---------------- WEBSOCKETS ----------------
    {
      number: "x",
      title: "WebSockets & Real-Time Communication",
      blocks: [
        { type: "p", text: "REST APIs (Unit 21) are request/response — the client always initiates. For genuinely real-time features (live chat, live scores, collaborative editing), a **WebSocket** keeps a persistent, two-way connection open, letting the server push data the instant it changes." },
        { type: "code", text: [
          "import 'dart:convert';",
          "import 'package:web_socket_channel/web_socket_channel.dart';",
          "",
          "class ChatService {",
          "  final channel = WebSocketChannel.connect(",
          "    Uri.parse('wss://example.com/chat'),",
          "  );",
          "",
          "  Stream<dynamic> get messages => channel.stream;",
          "",
          "  void sendMessage(String text) {",
          "    channel.sink.add(jsonEncode({'message': text}));",
          "  }",
          "",
          "  void close() {",
          "    channel.sink.close();",
          "  }",
          "}",
        ].join("\n") },
        { type: "code", text: [
          "// In a widget — pair the Stream directly with StreamBuilder (Unit 21)",
          "StreamBuilder(",
          "  stream: chatService.messages,",
          "  builder: (context, snapshot) {",
          "    if (!snapshot.hasData) return const Text('Waiting for messages...');",
          "    return Text('New message: ${snapshot.data}');",
          "  },",
          ")",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Always close a WebSocket channel (`channel.sink.close()`) when the screen using it is disposed — an open socket left dangling keeps consuming battery and network resources in the background." },
        { type: "keypoints", items: [
          "WebSockets keep a persistent connection open, allowing the server to push updates without the client polling repeatedly.",
          "`web_socket_channel` exposes an incoming `Stream` and an outgoing `sink` — the `Stream` half pairs naturally with `StreamBuilder`.",
          "Always close the channel when it's no longer needed, mirroring the disposal discipline used for controllers and animations.",
        ]},
      ],
    },

    // ---------------- ADVANCED FORMS ----------------
    {
      number: "x",
      title: "Advanced Forms & Multi-Step Wizards",
      blocks: [
        { type: "p", text: "Beyond single-screen forms (Unit 18), many real apps need multi-field cross-validation or a multi-step \"wizard\" flow — a registration process broken across several screens that still validates and submits as one logical unit." },
        { type: "h3", text: "Cross-Field Validation" },
        { type: "code", text: [
          "final _passwordController = TextEditingController();",
          "",
          "TextFormField(",
          "  decoration: const InputDecoration(labelText: 'Confirm Password'),",
          "  validator: (value) {",
          "    if (value != _passwordController.text) {",
          "      return 'Passwords do not match';",
          "    }",
          "    return null;",
          "  },",
          ")",
        ].join("\n") },
        { type: "h3", text: "A Simple Multi-Step Wizard with Stepper" },
        { type: "code", text: [
          "int _currentStep = 0;",
          "",
          "Stepper(",
          "  currentStep: _currentStep,",
          "  onStepContinue: () {",
          "    if (_currentStep < 2) {",
          "      setState(() => _currentStep++);",
          "    } else {",
          "      print('Wizard complete — submit all collected data');",
          "    }",
          "  },",
          "  onStepCancel: () {",
          "    if (_currentStep > 0) setState(() => _currentStep--);",
          "  },",
          "  steps: const [",
          "    Step(title: Text('Personal Details'), content: Text('Name, email...')),",
          "    Step(title: Text('Academic Details'), content: Text('Roll number, year...')),",
          "    Step(title: Text('Review'), content: Text('Confirm and submit')),",
          "  ],",
          ")",
        ].join("\n") },
        { type: "note", kind: "tip", text: "For a wizard spanning multiple full screens (rather than one scrollable `Stepper`), hold the shared, accumulated form data in a single object owned above all the steps — via `Provider`/`Riverpod` (Unit 20) — rather than trying to pass and merge partial data manually through `Navigator` route arguments." },
        { type: "keypoints", items: [
          "Cross-field validators compare against another field's current value, typically read from its `TextEditingController`.",
          "`Stepper` provides a ready-made, linear multi-step UI for forms that fit comfortably on one screen.",
          "For wizards spanning multiple full screens, centralize the shared form state above the steps rather than threading it through navigation arguments.",
        ]},
      ],
    },
  ],
};
