module.exports = {
  partTitle: "PART I — THE DART LANGUAGE",
  partSubtitle: "Foundations you need before Flutter makes sense",
  units: [
    // ---------------- UNIT 1 ----------------
    {
      number: "1",
      title: "Introduction to Dart",
      blocks: [
        { type: "p", text: "Dart is a client-optimized, object-oriented, garbage-collected programming language created by Google and first released in 2011. It was redesigned significantly for mobile and web app development, and today it exists primarily as the language that powers **Flutter**. Dart compiles in two directions: to native ARM/x64 machine code (used for fast-starting, high-performance mobile and desktop apps) and to JavaScript (used for the web). This dual compilation, combined with a **Just-In-Time (JIT)** compiler for development and an **Ahead-Of-Time (AOT)** compiler for release builds, is what gives Flutter apps both a fast development cycle (hot reload) and near-native runtime performance." },
        { type: "h3", text: "Why Dart for Flutter?" },
        { type: "ul", items: [
          "**Fast development cycles** — Dart's JIT compiler enables Flutter's *hot reload*, which injects updated code into a running app in under a second without losing app state.",
          "**Fast, predictable performance** — Dart's AOT compiler produces native ARM/x64 code, so release apps do not carry a JavaScript-bridge performance tax the way some cross-platform frameworks do.",
          "**Everything is an object** — including numbers, functions, and `null`. This gives Dart a small, consistent set of rules with very few special cases.",
          "**Sound null safety** — the compiler statically guarantees that a variable declared as non-nullable can never hold `null`, eliminating an entire category of runtime crashes.",
          "**Familiar C-style syntax** — curly braces, semicolons, and a syntax family close to Java, C#, and JavaScript make Dart quick to pick up for most programmers.",
        ]},
        { type: "h3", text: "Setting Up Dart" },
        { type: "p", text: "Dart ships bundled with the Flutter SDK, so installing Flutter also installs Dart. If you only want to experiment with the language itself (without Flutter), you can install the standalone Dart SDK from dart.dev, or write and run snippets instantly in **DartPad** (dartpad.dev) — a free, browser-based editor that requires no installation and is the fastest way to try the examples in this manual." },
        { type: "p", text: "To check that Dart is available from your terminal once the SDK is installed:" },
        { type: "code", text: [
          "dart --version",
          "# Expected output looks like:",
          "# Dart SDK version: 3.5.0 (stable) ...",
        ].join("\n") },
        { type: "h3", text: "Your First Dart Program" },
        { type: "p", text: "Every Dart application begins execution at a top-level function named `main()`. Save the following as `hello.dart`:" },
        { type: "code", text: [
          "void main() {",
          "  print('Hello, World!');",
          "}",
        ].join("\n") },
        { type: "p", text: "Run it from the terminal with:" },
        { type: "code", text: "dart run hello.dart" },
        { type: "note", kind: "tip", text: "`print()` is Dart's built-in function for writing a line of text to the console. It accepts any object and calls `toString()` on it automatically, so `print(42)` and `print([1, 2, 3])` both work without extra conversion." },
        { type: "keypoints", items: [
          "Dart is the language behind Flutter, designed by Google for fast development and fast execution.",
          "JIT compilation powers hot reload during development; AOT compilation produces optimized native code for release.",
          "DartPad lets you run Dart in the browser with zero setup — ideal while working through this manual.",
          "Execution always starts at the top-level `main()` function.",
        ]},
      ],
    },

    // ---------------- UNIT 2 ----------------
    {
      number: "2",
      title: "Variables, Data Types & Operators",
      blocks: [
        { type: "p", text: "Dart is statically typed but supports **type inference**, meaning the compiler can often determine a variable's type from the value assigned to it, without you writing the type explicitly." },
        { type: "h3", text: "Declaring Variables" },
        { type: "code", text: [
          "var name = 'Sudhakar';       // inferred as String",
          "var age = 40;                // inferred as int",
          "String department = 'AI&DS'; // explicit type",
          "final joinedYear = 2015;     // value set once, at runtime",
          "const pi = 3.14159;          // value fixed at compile time",
        ].join("\n") },
        { type: "table", header: ["Keyword", "Reassignable?", "When the value is fixed", "Typical use"],
          rows: [
            ["`var`", "Yes", "Any time", "General-purpose, type inferred once"],
            ["Explicit type (`int`, `String`, …)", "Yes", "Any time", "When you want the type visible for clarity"],
            ["`final`", "No", "Set once, at runtime", "Values known only when the app runs (e.g. `DateTime.now()`)"],
            ["`const`", "No", "Set once, at compile time", "Truly constant values (e.g. `3.14159`, fixed strings)"],
          ]},
        { type: "h3", text: "Built-in Data Types" },
        { type: "table", header: ["Type", "Description", "Example"],
          rows: [
            ["`int`", "Whole numbers (64-bit on native platforms)", "`int score = 95;`"],
            ["`double`", "64-bit floating point numbers", "`double gpa = 9.2;`"],
            ["`num`", "Superclass of both `int` and `double`", "`num value = 10; value = 10.5;`"],
            ["`String`", "Sequence of UTF-16 characters", "`String city = 'Vijayawada';`"],
            ["`bool`", "`true` or `false`", "`bool isActive = true;`"],
            ["`List<T>`", "Ordered collection", "`List<int> marks = [80, 90, 100];`"],
            ["`Set<T>`", "Unordered collection of unique items", "`Set<String> tags = {'ai', 'ml'};`"],
            ["`Map<K,V>`", "Key–value pairs", "`Map<String,int> ages = {'A': 20};`"],
            ["`dynamic`", "Type checking deferred to runtime", "`dynamic x = 10; x = 'now a string';`"],
          ]},
        { type: "h3", text: "String Interpolation & Multi-line Strings" },
        { type: "code", text: [
          "String name = 'Sudhakar';",
          "int papers = 118;",
          "print('Author: $name has $papers indexed records.');",
          "print('Next milestone: ${papers + 2} papers');",
          "",
          "String note = '''",
          "This is a multi-line string.",
          "It preserves line breaks exactly as written.",
          "''';",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Use `${expression}` for any expression more complex than a bare variable name; a bare variable only needs `$variableName` without braces." },
        { type: "h3", text: "Operators" },
        { type: "table", header: ["Category", "Operators", "Notes"],
          rows: [
            ["Arithmetic", "`+  -  *  /  ~/  %`", "`~/` is integer (floor) division: `7 ~/ 2` is `3`"],
            ["Relational", "`==  !=  >  <  >=  <=`", "Return a `bool`"],
            ["Logical", "`&&  ||  !`", "Short-circuit evaluation"],
            ["Assignment", "`=  +=  -=  *=  /=  ??=`", "`??=` assigns only if the variable is currently `null`"],
            ["Type test", "`is  is!`", "`if (value is String) { ... }`"],
            ["Cascade", "`..`", "Chain multiple calls on the same object"],
            ["Null-aware", "`??  ?.  !`", "Covered fully in Unit 10 (Null Safety)"],
          ]},
        { type: "code", text: [
          "// Cascade notation — call several members on the same object",
          "var buffer = StringBuffer()",
          "  ..write('Hello')",
          "  ..write(', ')",
          "  ..write('Flutter!');",
          "print(buffer.toString()); // Hello, Flutter!",
        ].join("\n") },
        { type: "keypoints", items: [
          "`var` infers a type once; `dynamic` allows the type to change at runtime.",
          "`final` is set once at runtime; `const` is fixed at compile time.",
          "`String` interpolation uses `$variable` or `${expression}`.",
          "The cascade operator `..` lets you chain calls on one object without repeating its name.",
        ]},
      ],
    },

    // ---------------- UNIT 3 ----------------
    {
      number: "3",
      title: "Control Flow Statements",
      blocks: [
        { type: "h3", text: "Conditional Statements" },
        { type: "code", text: [
          "int marks = 78;",
          "",
          "if (marks >= 90) {",
          "  print('Grade: A');",
          "} else if (marks >= 75) {",
          "  print('Grade: B');",
          "} else {",
          "  print('Grade: C');",
          "}",
          "",
          "// Conditional (ternary) expression",
          "String result = marks >= 40 ? 'Pass' : 'Fail';",
        ].join("\n") },
        { type: "h3", text: "Switch Statements" },
        { type: "p", text: "Dart 3 extended `switch` to support pattern matching, but the classic form is still the one you will use most often for simple value matching:" },
        { type: "code", text: [
          "String grade = 'B';",
          "",
          "switch (grade) {",
          "  case 'A':",
          "    print('Excellent');",
          "    break;",
          "  case 'B':",
          "    print('Good');",
          "    break;",
          "  default:",
          "    print('Needs improvement');",
          "}",
          "",
          "// Dart 3 switch expression (more concise, returns a value)",
          "String remark = switch (grade) {",
          "  'A' => 'Excellent',",
          "  'B' => 'Good',",
          "  _   => 'Needs improvement',",
          "};",
        ].join("\n") },
        { type: "h3", text: "Loops" },
        { type: "code", text: [
          "// for loop",
          "for (int i = 1; i <= 5; i++) {",
          "  print('Count: $i');",
          "}",
          "",
          "// for-in loop — iterating a collection",
          "List<String> subjects = ['AI', 'DS', 'ML'];",
          "for (var subject in subjects) {",
          "  print(subject);",
          "}",
          "",
          "// while loop — condition checked before each iteration",
          "int n = 0;",
          "while (n < 3) {",
          "  print('n = $n');",
          "  n++;",
          "}",
          "",
          "// do-while loop — body always runs at least once",
          "int m = 0;",
          "do {",
          "  print('m = $m');",
          "  m++;",
          "} while (m < 3);",
        ].join("\n") },
        { type: "h3", text: "break, continue & Labeled Loops" },
        { type: "code", text: [
          "outerLoop:",
          "for (int i = 0; i < 3; i++) {",
          "  for (int j = 0; j < 3; j++) {",
          "    if (j == 1) continue;        // skip this inner iteration",
          "    if (i == 2) break outerLoop;  // exit the labeled outer loop",
          "    print('i=$i, j=$j');",
          "  }",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "Dart's classic `switch` needs an explicit `break` per case; the newer switch *expression* (`=>`) does not.",
          "`for-in` is the idiomatic way to loop over any `Iterable` (List, Set, etc.).",
          "`do-while` guarantees the loop body executes at least once.",
          "Labels let `break`/`continue` target an outer loop from within a nested one.",
        ]},
      ],
    },

    // ---------------- UNIT 4 ----------------
    {
      number: "4",
      title: "Functions",
      blocks: [
        { type: "p", text: "Functions are first-class objects in Dart — they can be stored in variables, passed as arguments, and returned from other functions. This is essential in Flutter, where callbacks such as `onPressed` are simply functions passed as widget parameters." },
        { type: "h3", text: "Basic Function Syntax" },
        { type: "code", text: [
          "int add(int a, int b) {",
          "  return a + b;",
          "}",
          "",
          "// Arrow syntax — for a function body that is a single expression",
          "int square(int x) => x * x;",
          "",
          "void main() {",
          "  print(add(2, 3));    // 5",
          "  print(square(4));    // 16",
          "}",
        ].join("\n") },
        { type: "h3", text: "Optional Positional Parameters" },
        { type: "code", text: [
          "String greet(String name, [String? title]) {",
          "  if (title != null) return 'Hello, $title $name';",
          "  return 'Hello, $name';",
          "}",
          "",
          "print(greet('Sudhakar'));            // Hello, Sudhakar",
          "print(greet('Sudhakar', 'Dr.'));     // Hello, Dr. Sudhakar",
        ].join("\n") },
        { type: "h3", text: "Named Parameters" },
        { type: "p", text: "Named parameters are wrapped in `{}` and are the pattern you will see constantly in Flutter widget constructors. Mark a named parameter `required` when the caller must supply it." },
        { type: "code", text: [
          "void printProfile({required String name, int age = 18}) {",
          "  print('$name is $age years old');",
          "}",
          "",
          "printProfile(name: 'Anita');            // Anita is 18 years old",
          "printProfile(name: 'Ravi', age: 21);    // Ravi is 21 years old",
        ].join("\n") },
        { type: "note", kind: "tip", text: "This is exactly why Flutter widgets are constructed like `Text('Hello', style: TextStyle(fontSize: 20))` — the widget's constructor simply uses named parameters." },
        { type: "h3", text: "Anonymous Functions & Closures" },
        { type: "code", text: [
          "List<int> numbers = [1, 2, 3, 4, 5];",
          "",
          "// Anonymous function passed directly to forEach",
          "numbers.forEach((n) {",
          "  print('Number: $n');",
          "});",
          "",
          "// A closure — the returned function 'closes over' the counter variable",
          "Function makeCounter() {",
          "  int count = 0;",
          "  return () {",
          "    count++;",
          "    return count;",
          "  };",
          "}",
          "",
          "void main() {",
          "  var counter = makeCounter();",
          "  print(counter()); // 1",
          "  print(counter()); // 2",
          "}",
        ].join("\n") },
        { type: "h3", text: "Higher-Order Functions" },
        { type: "code", text: [
          "List<int> marks = [55, 90, 40, 72, 88];",
          "",
          "var passed = marks.where((m) => m >= 50).toList();  // [55, 90, 72, 88]",
          "var doubled = marks.map((m) => m * 2).toList();     // [110, 180, 80, 144, 176]",
          "var total   = marks.reduce((a, b) => a + b);        // 345",
          "var anyFail = marks.any((m) => m < 50);             // true",
        ].join("\n") },
        { type: "keypoints", items: [
          "Functions are objects — they can be assigned, passed, and returned like any value.",
          "`[optional]` positional parameters and `{named}` parameters both make arguments optional; `required` forces a named parameter to be supplied.",
          "Arrow syntax (`=>`) is shorthand for a function body that returns a single expression.",
          "`where`, `map`, `reduce`, and `any` are the functional-style methods you'll use constantly when transforming lists.",
        ]},
      ],
    },

    // ---------------- UNIT 5 ----------------
    {
      number: "5",
      title: "Collections — List, Set & Map",
      blocks: [
        { type: "h3", text: "List — an ordered, indexable collection" },
        { type: "code", text: [
          "List<String> subjects = ['AI', 'DS', 'ML'];",
          "subjects.add('DL');                 // ['AI', 'DS', 'ML', 'DL']",
          "subjects.insert(1, 'Stats');         // insert at index 1",
          "subjects.remove('ML');",
          "print(subjects[0]);                  // AI",
          "print(subjects.length);              // 4",
          "",
          "// A fixed-length, immutable list",
          "final List<int> readOnly = List.unmodifiable([1, 2, 3]);",
        ].join("\n") },
        { type: "h3", text: "Set — unique, unordered elements" },
        { type: "code", text: [
          "Set<String> tags = {'flutter', 'dart', 'flutter'}; // duplicate is dropped",
          "print(tags);              // {flutter, dart}",
          "print(tags.contains('dart')); // true",
          "",
          "var a = {1, 2, 3};",
          "var b = {2, 3, 4};",
          "print(a.union(b));         // {1, 2, 3, 4}",
          "print(a.intersection(b));  // {2, 3}",
        ].join("\n") },
        { type: "h3", text: "Map — key-value pairs" },
        { type: "code", text: [
          "Map<String, int> credits = {",
          "  'Flutter Lab': 2,",
          "  'Explainable AI': 4,",
          "};",
          "",
          "credits['Data Science'] = 3;        // add a new entry",
          "print(credits['Flutter Lab']);       // 2",
          "print(credits.containsKey('AI'));    // false",
          "",
          "credits.forEach((subject, credit) {",
          "  print('$subject: $credit credits');",
          "});",
        ].join("\n") },
        { type: "h3", text: "Collection If / For & the Spread Operator" },
        { type: "p", text: "Dart allows control-flow-like syntax directly inside a collection literal — extremely useful when building widget lists conditionally in Flutter." },
        { type: "code", text: [
          "bool showExtra = true;",
          "List<int> base = [1, 2, 3];",
          "",
          "List<int> combined = [",
          "  0,",
          "  ...base,                 // spread operator — unpacks all elements",
          "  if (showExtra) 4,        // collection-if",
          "  for (var i in [5, 6]) i, // collection-for",
          "];",
          "print(combined); // [0, 1, 2, 3, 4, 5, 6]",
        ].join("\n") },
        { type: "table", header: ["Collection", "Ordered?", "Duplicates?", "Access by"],
          rows: [
            ["`List`", "Yes", "Allowed", "Index (`list[0]`)"],
            ["`Set`", "No", "Not allowed", "Value lookup (`contains`)"],
            ["`Map`", "Insertion order preserved", "Keys unique, values can repeat", "Key (`map['key']`)"],
          ]},
        { type: "keypoints", items: [
          "`List`, `Set`, and `Map` are the three core collection types, each with a distinct purpose.",
          "The spread operator `...` and collection-if/-for let you build a collection declaratively — the same technique you'll use to build widget children lists in Flutter.",
          "`List.unmodifiable()` and the `const` collection literals create collections that cannot be changed after creation.",
        ]},
      ],
    },

    // ---------------- UNIT 6 ----------------
    {
      number: "6",
      title: "Object-Oriented Programming in Dart",
      blocks: [
        { type: "p", text: "Everything in Dart — including numbers and functions — is an instance of a class. Understanding classes, constructors, and inheritance is essential before Flutter's widget classes will make sense, since every widget is itself a Dart class." },
        { type: "h3", text: "Classes & Objects" },
        { type: "code", text: [
          "class Student {",
          "  String name;",
          "  int rollNumber;",
          "",
          "  // Standard constructor",
          "  Student(this.name, this.rollNumber);",
          "",
          "  void display() {",
          "    print('$rollNumber: $name');",
          "  }",
          "}",
          "",
          "void main() {",
          "  var s1 = Student('Anita', 101);",
          "  s1.display(); // 101: Anita",
          "}",
        ].join("\n") },
        { type: "h3", text: "Named & Factory Constructors" },
        { type: "code", text: [
          "class Point {",
          "  double x, y;",
          "",
          "  Point(this.x, this.y);",
          "",
          "  // Named constructor — an alternative way to build the same class",
          "  Point.origin() : x = 0, y = 0;",
          "",
          "  // Factory constructor — has full control over what gets returned,",
          "  // useful for caching or returning a subtype",
          "  factory Point.fromMap(Map<String, double> map) {",
          "    return Point(map['x']!, map['y']!);",
          "  }",
          "}",
          "",
          "var p1 = Point(3, 4);",
          "var p2 = Point.origin();",
          "var p3 = Point.fromMap({'x': 1.0, 'y': 2.0});",
        ].join("\n") },
        { type: "h3", text: "Inheritance" },
        { type: "code", text: [
          "class Animal {",
          "  String name;",
          "  Animal(this.name);",
          "  void makeSound() => print('$name makes a sound');",
          "}",
          "",
          "class Dog extends Animal {",
          "  Dog(String name) : super(name);",
          "",
          "  @override",
          "  void makeSound() => print('$name barks');",
          "}",
          "",
          "void main() {",
          "  Animal a = Dog('Tommy');",
          "  a.makeSound(); // Tommy barks",
          "}",
        ].join("\n") },
        { type: "h3", text: "Abstract Classes & Interfaces" },
        { type: "p", text: "Dart has no separate `interface` keyword — **every class implicitly defines an interface**. Use `implements` to adopt that interface without inheriting behaviour, or `extends` an `abstract class` to inherit both a contract and shared implementation." },
        { type: "code", text: [
          "abstract class Shape {",
          "  double area(); // no body — subclasses must implement this",
          "}",
          "",
          "class Circle extends Shape {",
          "  double radius;",
          "  Circle(this.radius);",
          "",
          "  @override",
          "  double area() => 3.14159 * radius * radius;",
          "}",
        ].join("\n") },
        { type: "h3", text: "Mixins" },
        { type: "p", text: "A mixin lets you reuse a chunk of functionality across multiple, otherwise unrelated class hierarchies — Dart's answer to \"multiple inheritance\" without the classic diamond problem. Flutter itself relies heavily on mixins, e.g. `SingleTickerProviderStateMixin` for animations." },
        { type: "code", text: [
          "mixin Logger {",
          "  void log(String message) => print('[LOG] $message');",
          "}",
          "",
          "class NetworkService with Logger {",
          "  void fetchData() {",
          "    log('Fetching data...');",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Enums" },
        { type: "code", text: [
          "enum Status { pending, approved, rejected }",
          "",
          "// Enhanced enums (Dart 2.17+) can carry fields and methods",
          "enum Priority {",
          "  low(1), medium(2), high(3);",
          "  final int level;",
          "  const Priority(this.level);",
          "}",
          "",
          "void main() {",
          "  var s = Status.approved;",
          "  print(s);              // Status.approved",
          "  print(Priority.high.level); // 3",
          "}",
        ].join("\n") },
        { type: "table", header: ["Keyword", "Purpose"],
          rows: [
            ["`extends`", "Inherit implementation from exactly one superclass"],
            ["`implements`", "Adopt a class's interface without inheriting its implementation (must re-implement every member)"],
            ["`with`", "Mix in reusable behaviour from one or more mixins"],
            ["`abstract`", "Declare a class that cannot be instantiated directly, and may contain unimplemented methods"],
          ]},
        { type: "keypoints", items: [
          "Every class defines an implicit interface — `implements` uses that; `extends` inherits actual behaviour.",
          "Named and factory constructors give you multiple, clearly-labelled ways to build the same class.",
          "Mixins (`with`) let you share behaviour across unrelated class hierarchies — heavily used inside Flutter itself.",
          "Enhanced enums can carry fields, constructors, and methods, not just a list of names.",
        ]},
      ],
    },

    // ---------------- UNIT 7 ----------------
    {
      number: "7",
      title: "Generics",
      blocks: [
        { type: "p", text: "Generics let you write a class or function that works with any type while still catching type errors at compile time, instead of relying on `dynamic` and discovering mistakes at runtime. Dart's own collection types (`List<T>`, `Map<K,V>`) are generic classes, and Flutter's `State<T extends StatefulWidget>` is a generic class too." },
        { type: "h3", text: "Generic Classes" },
        { type: "code", text: [
          "class Box<T> {",
          "  T value;",
          "  Box(this.value);",
          "",
          "  void show() => print('Box contains: $value');",
          "}",
          "",
          "void main() {",
          "  var intBox = Box<int>(42);",
          "  var strBox = Box<String>('Flutter');",
          "  intBox.show();  // Box contains: 42",
          "  strBox.show();  // Box contains: Flutter",
          "}",
        ].join("\n") },
        { type: "h3", text: "Generic Functions" },
        { type: "code", text: [
          "T firstElement<T>(List<T> items) {",
          "  return items[0];",
          "}",
          "",
          "print(firstElement<String>(['a', 'b', 'c'])); // a",
          "print(firstElement<int>([10, 20, 30]));       // 10",
        ].join("\n") },
        { type: "h3", text: "Bounded Type Parameters" },
        { type: "code", text: [
          "// T must be a num or a subtype of num (int, double)",
          "T largest<T extends num>(T a, T b) => a > b ? a : b;",
          "",
          "print(largest<int>(3, 7));       // 7",
          "print(largest<double>(2.5, 1.1)); // 2.5",
        ].join("\n") },
        { type: "keypoints", items: [
          "Generics give you type safety without duplicating code for every possible type.",
          "`<T extends SomeType>` restricts the generic type to `SomeType` or its subtypes.",
          "You'll see generics constantly in Flutter: `List<Widget>`, `Future<String>`, `State<MyWidget>`.",
        ]},
      ],
    },

    // ---------------- UNIT 8 ----------------
    {
      number: "8",
      title: "Exception Handling",
      blocks: [
        { type: "p", text: "Dart uses `try`/`catch`/`finally`, similar to Java or C#. All Dart exceptions are unchecked — the compiler does not force you to catch them — so disciplined use of `try`/`catch` around risky operations (network calls, parsing, file access) is a habit worth building early." },
        { type: "h3", text: "Basic try-catch" },
        { type: "code", text: [
          "void divide(int a, int b) {",
          "  try {",
          "    print(a ~/ b);",
          "  } on IntegerDivisionByZeroException {",
          "    print('Cannot divide by zero!');",
          "  } catch (e) {",
          "    print('Something went wrong: $e');",
          "  } finally {",
          "    print('Division attempt finished.');",
          "  }",
          "}",
          "",
          "void main() {",
          "  divide(10, 0);",
          "}",
        ].join("\n") },
        { type: "h3", text: "Custom Exceptions" },
        { type: "code", text: [
          "class InvalidMarksException implements Exception {",
          "  final String message;",
          "  InvalidMarksException(this.message);",
          "",
          "  @override",
          "  String toString() => 'InvalidMarksException: $message';",
          "}",
          "",
          "void setMarks(int marks) {",
          "  if (marks < 0 || marks > 100) {",
          "    throw InvalidMarksException('Marks must be between 0 and 100');",
          "  }",
          "  print('Marks set to $marks');",
          "}",
          "",
          "void main() {",
          "  try {",
          "    setMarks(150);",
          "  } on InvalidMarksException catch (e) {",
          "    print(e);",
          "  }",
          "}",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Catching a generic `catch (e)` swallows every possible error, including bugs you'd rather discover during testing. Prefer `on SpecificException catch (e)` where you can, and reserve the generic catch for a final safety net." },
        { type: "keypoints", items: [
          "`on ExceptionType` catches a specific exception; a bare `catch (e)` catches anything.",
          "`finally` always runs, whether or not an exception was thrown — ideal for closing streams or resetting UI loading state.",
          "Implementing the `Exception` interface (`implements Exception`) is the idiomatic way to define your own exception types.",
        ]},
      ],
    },

    // ---------------- UNIT 9 ----------------
    {
      number: "9",
      title: "Asynchronous Programming — Future, async/await & Stream",
      blocks: [
        { type: "p", text: "Almost everything meaningful an app does — reading a file, calling an API, querying a database — takes time and should not block the UI thread while it happens. Dart handles this with a single-threaded **event loop** plus two core types: **`Future`** (a value that will be available *once*, later) and **`Stream`** (a sequence of values delivered *over time*)." },
        { type: "h3", text: "Future & async/await" },
        { type: "code", text: [
          "Future<String> fetchUserName() async {",
          "  await Future.delayed(Duration(seconds: 2)); // simulate network delay",
          "  return 'Sudhakar';",
          "}",
          "",
          "void main() async {",
          "  print('Fetching...');",
          "  String name = await fetchUserName();",
          "  print('Got: $name');",
          "}",
          "// Output:",
          "// Fetching...",
          "// (2 second pause)",
          "// Got: Sudhakar",
        ].join("\n") },
        { type: "p", text: "A function marked `async` always returns a `Future`, even if you write a plain `return value;` inside it — Dart wraps the value for you. `await` pauses execution *of that function only* until the `Future` completes; it does not block the rest of the app." },
        { type: "h3", text: "Handling Errors in async Code" },
        { type: "code", text: [
          "Future<int> riskyOperation() async {",
          "  throw Exception('Network error');",
          "}",
          "",
          "void main() async {",
          "  try {",
          "    await riskyOperation();",
          "  } catch (e) {",
          "    print('Caught: $e');",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Chaining Futures with .then()" },
        { type: "code", text: [
          "fetchUserName()",
          "  .then((name) => print('Hello, $name'))",
          "  .catchError((e) => print('Error: $e'))",
          "  .whenComplete(() => print('Done'));",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`async`/`await` and `.then()` chains are two syntaxes for the same underlying mechanism. Prefer `async`/`await` for readability — it reads top-to-bottom like synchronous code — and reach for `.then()` mainly when you need to fire-and-forget without pausing the current function." },
        { type: "h3", text: "Stream — a sequence of asynchronous values" },
        { type: "code", text: [
          "Stream<int> countStream() async* {",
          "  for (int i = 1; i <= 5; i++) {",
          "    await Future.delayed(Duration(seconds: 1));",
          "    yield i;",
          "  }",
          "}",
          "",
          "void main() async {",
          "  await for (var value in countStream()) {",
          "    print('Received: $value');",
          "  }",
          "  print('Stream finished');",
          "}",
        ].join("\n") },
        { type: "table", header: ["Concept", "Delivers", "Typical Flutter use"],
          rows: [
            ["`Future<T>`", "A single value, once, later", "One-off API call, reading a file"],
            ["`Stream<T>`", "Zero or more values, over time", "Live text field changes, `StreamBuilder`, real-time database listeners"],
            ["`async*` / `yield`", "Builds a `Stream` incrementally", "Generating a sequence of values lazily"],
          ]},
        { type: "keypoints", items: [
          "`Future` = one value later; `Stream` = many values over time.",
          "`async` + `await` is the readable way to work with Futures; the function must be marked `async` to use `await` inside it.",
          "`await for` iterates a `Stream` the same way `for-in` iterates a `List`.",
          "Always wrap `await` calls that can fail in `try`/`catch` — an uncaught exception inside an `async` function completes its `Future` with an error rather than crashing immediately, which is easy to miss.",
        ]},
      ],
    },

    // ---------------- UNIT 10 ----------------
    {
      number: "10",
      title: "Null Safety",
      blocks: [
        { type: "p", text: "Since Dart 2.12, **sound null safety** is the default for all new code. The compiler tracks, for every variable, whether `null` is a legal value — and refuses to compile code where a non-nullable variable might end up `null`. This eliminates the classic \"null pointer / NoSuchMethodError on null\" crash at compile time rather than runtime." },
        { type: "h3", text: "Nullable vs Non-Nullable Types" },
        { type: "code", text: [
          "String name = 'Sudhakar';   // non-nullable — can never be null",
          "String? nickname;           // nullable — defaults to null, marked with '?'",
          "",
          "// name = null;   // Compile-time error — not allowed",
          "nickname = null;  // OK — declared nullable",
        ].join("\n") },
        { type: "h3", text: "Null-Aware Operators" },
        { type: "table", header: ["Operator", "Meaning", "Example"],
          rows: [
            ["`?.`", "Call a member only if the object isn't null", "`user?.name`"],
            ["`??`", "Fallback value if the expression is null", "`nickname ?? 'Guest'`"],
            ["`??=`", "Assign only if the variable is currently null", "`nickname ??= 'Guest'`"],
            ["`!`", "Assert to the compiler \"this is not null\" (throws at runtime if wrong)", "`nickname!.length`"],
          ]},
        { type: "code", text: [
          "String? nickname;",
          "print(nickname?.toUpperCase());     // null (safe — no crash)",
          "print(nickname ?? 'Guest');          // Guest",
          "nickname ??= 'Ravi';",
          "print(nickname);                     // Ravi",
          "print(nickname!.toUpperCase());      // RAVI — safe now that we know it's set",
        ].join("\n") },
        { type: "note", kind: "warning", text: "The `!` (null-assertion) operator is a promise you're making to the compiler, not a safety check. If the value actually is `null` at runtime, `!` throws immediately. Use it only when you are certain — e.g. right after a `null` check — and prefer `??` or `?.` wherever a sensible fallback exists." },
        { type: "h3", text: "The `late` Keyword" },
        { type: "p", text: "`late` tells the compiler \"trust me, this non-nullable variable will be assigned before it's used\" — useful for values initialized in `initState()` in a Flutter `StatefulWidget`, where the field must be declared before it's set." },
        { type: "code", text: [
          "class UserSession {",
          "  late String token; // not assigned yet, but promised to be non-null before use",
          "",
          "  void login(String t) {",
          "    token = t;",
          "  }",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "A type followed by `?` is nullable; without `?`, the compiler guarantees the variable is never null.",
          "`??`, `?.`, and `??=` let you handle possible `null` values gracefully.",
          "`!` forcibly asserts non-null and will throw at runtime if you're wrong — use sparingly.",
          "`late` defers a non-nullable variable's initialization, common for fields set inside `initState()`.",
        ]},
      ],
    },

    // ---------------- UNIT 11 ----------------
    {
      number: "11",
      title: "Libraries, Packages & pub.dev",
      blocks: [
        { type: "p", text: "Every Dart file is implicitly its own library. You share code between files with `import`, and share code between *projects* by publishing or consuming packages through **pub.dev**, the official Dart/Flutter package repository." },
        { type: "h3", text: "Importing Files" },
        { type: "code", text: [
          "// core Dart library",
          "import 'dart:math';",
          "",
          "// a third-party package (declared in pubspec.yaml)",
          "import 'package:http/http.dart' as http;",
          "",
          "// a file from within your own project",
          "import 'models/student.dart';",
          "",
          "void main() {",
          "  print(sqrt(16)); // 4.0 — from dart:math",
          "}",
        ].join("\n") },
        { type: "h3", text: "pubspec.yaml — the project manifest" },
        { type: "p", text: "Every Dart/Flutter project has a `pubspec.yaml` file at its root declaring the project's name, SDK constraints, and dependencies." },
        { type: "code", text: [
          "name: my_app",
          "description: A sample Flutter application.",
          "version: 1.0.0+1",
          "",
          "environment:",
          "  sdk: '>=3.0.0 <4.0.0'",
          "",
          "dependencies:",
          "  flutter:",
          "    sdk: flutter",
          "  http: ^1.2.0",
          "  provider: ^6.1.0",
          "",
          "dev_dependencies:",
          "  flutter_test:",
          "    sdk: flutter",
        ].join("\n") },
        { type: "p", text: "After editing `pubspec.yaml`, fetch the declared packages with:" },
        { type: "code", text: "flutter pub get" },
        { type: "note", kind: "tip", text: "The caret (`^1.2.0`) means \"any version compatible with 1.2.0\" — i.e. `>=1.2.0 <2.0.0`. This lets your project automatically receive bug-fix and minor updates without risking a breaking major-version change." },
        { type: "h3", text: "Organizing Your Own Code into Libraries" },
        { type: "code", text: [
          "// file: utils/validators.dart",
          "bool isValidEmail(String email) => email.contains('@');",
          "",
          "// file: main.dart",
          "import 'utils/validators.dart';",
          "",
          "void main() {",
          "  print(isValidEmail('test@lbrce.ac.in')); // true",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "`import 'dart:...'` brings in core SDK libraries; `import 'package:...'` brings in third-party or your own package's code.",
          "`pubspec.yaml` declares every dependency your project needs; `flutter pub get` downloads them.",
          "Caret syntax (`^x.y.z`) in version constraints allows safe, non-breaking updates automatically.",
        ]},
      ],
    },
  ],
};
