module.exports = {
  partTitle: "PART II — THE FLUTTER FRAMEWORK",
  partSubtitle: "From widgets to shipped applications",
  units: [
    // ---------------- UNIT 12 ----------------
    {
      number: "12",
      title: "Introduction to Flutter",
      blocks: [
        { type: "p", text: "Flutter is Google's open-source UI toolkit for building natively compiled applications for mobile, web, and desktop from a **single Dart codebase**. Unlike frameworks that wrap native platform widgets, Flutter draws every pixel itself using its own high-performance rendering engine (based on the Impeller/Skia graphics engines), which is why a Flutter button looks and behaves identically on Android, iOS, web, and desktop." },
        { type: "h3", text: "How Flutter Renders a Screen" },
        { type: "p", text: "Everything you see on screen in Flutter is a **widget** — and widgets themselves are lightweight, immutable configuration objects, not the actual pixels. When something changes, Flutter doesn't repaint the whole screen; it rebuilds only the affected part of a tree of three parallel structures:" },
        { type: "ul", items: [
          "**Widget tree** — the declarative description of what the UI should look like (what you write).",
          "**Element tree** — the mutable, live instantiation that manages a widget's lifecycle and links a widget to its position in the tree.",
          "**Render tree (RenderObject)** — the layer that actually handles layout, painting, and hit-testing.",
        ]},
        { type: "note", kind: "tip", text: "You will spend almost all of your time working with the widget tree; Elements and RenderObjects work behind the scenes and you rarely touch them directly unless you're building highly custom, low-level widgets." },
        { type: "h3", text: "Flutter vs Other Approaches" },
        { type: "table", header: ["Approach", "Example", "How UI is rendered"],
          rows: [
            ["Native", "Swift/Kotlin", "Platform's own native widgets, separate codebase per platform"],
            ["WebView-based hybrid", "Cordova/Ionic", "HTML/CSS/JS rendered in an embedded browser"],
            ["Native-bridge", "React Native", "JavaScript logic calls out to real native widgets via a bridge"],
            ["Flutter", "Dart + Flutter", "Flutter's own engine draws every pixel directly, one codebase, no bridge"],
          ]},
        { type: "keypoints", items: [
          "Flutter draws its own UI rather than wrapping native platform widgets, giving pixel-perfect consistency across platforms.",
          "\"Everything is a widget\" — text, padding, layout, even animations are all expressed as widgets.",
          "The Widget → Element → RenderObject pipeline is what makes Flutter fast: only the parts of the tree that actually changed are rebuilt and repainted.",
        ]},
      ],
    },

    // ---------------- UNIT 13 ----------------
    {
      number: "13",
      title: "Setting Up the Development Environment",
      blocks: [
        { type: "h3", text: "Installing the Flutter SDK" },
        { type: "ol", items: [
          "Download the Flutter SDK for your OS from flutter.dev and extract it to a permanent location (e.g. `C:\\src\\flutter` on Windows or `~/development/flutter` on macOS/Linux).",
          "Add the `flutter/bin` directory to your system `PATH`.",
          "Run `flutter doctor` in a terminal — this checks your setup and tells you exactly what's missing.",
        ]},
        { type: "code", text: [
          "flutter doctor",
          "",
          "# Sample output:",
          "# [✓] Flutter (Channel stable, 3.24.0)",
          "# [✓] Android toolchain - develop for Android devices",
          "# [✗] Xcode - develop for iOS and macOS (not installed)",
          "# [✓] Chrome - develop for the web",
          "# [✓] Android Studio",
          "# [✓] Connected device (1 available)",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Run `flutter doctor` again after installing anything it flags — it re-checks every requirement and tells you exactly what's still outstanding." },
        { type: "h3", text: "Choosing an IDE" },
        { type: "table", header: ["IDE", "Notes"],
          rows: [
            ["Visual Studio Code", "Lightweight, install the official \"Flutter\" and \"Dart\" extensions. Most widely used for Flutter."],
            ["Android Studio / IntelliJ", "Full-featured, built-in Android emulator management, official Flutter plugin available."],
          ]},
        { type: "h3", text: "Creating and Running Your First Project" },
        { type: "code", text: [
          "flutter create my_first_app",
          "cd my_first_app",
          "flutter run",
        ].join("\n") },
        { type: "p", text: "`flutter run` builds a debug version and launches it on any connected device, emulator, or in Chrome. While it's running, three keyboard shortcuts matter most in the terminal:" },
        { type: "table", header: ["Key", "Action"],
          rows: [
            ["`r`", "Hot reload — pushes your latest code changes into the running app in under a second, preserving app state"],
            ["`R`", "Hot restart — resets the app's state and rebuilds it from scratch, faster than a full re-run"],
            ["`q`", "Quit the running app"],
          ]},
        { type: "keypoints", items: [
          "`flutter doctor` is the first command to run whenever something in your setup seems wrong.",
          "`flutter create <name>` scaffolds a new, ready-to-run project.",
          "Hot reload (`r`) is one of Flutter's signature productivity features — use it constantly during UI development.",
        ]},
      ],
    },

    // ---------------- UNIT 14 ----------------
    {
      number: "14",
      title: "Anatomy of a Flutter Project",
      blocks: [
        { type: "p", text: "Running `flutter create` scaffolds a standard folder structure. Understanding what each folder is for will save you a lot of confusion later." },
        { type: "table", header: ["Folder / File", "Purpose"],
          rows: [
            ["`lib/`", "Your Dart source code lives here. `lib/main.dart` is the entry point."],
            ["`android/`, `ios/`", "Native platform project files — you'll rarely edit these directly, mostly for platform-specific configuration (permissions, app icons, signing)."],
            ["`web/`", "Files needed for the web build target (e.g. `index.html`)."],
            ["`test/`", "Automated test files, run with `flutter test`."],
            ["`pubspec.yaml`", "Project manifest — dependencies, assets, fonts, metadata (see Unit 11)."],
            ["`pubspec.lock`", "Auto-generated; pins exact resolved versions of every dependency."],
            ["`build/`", "Auto-generated build output — never edit or commit this."],
          ]},
        { type: "h3", text: "The Default main.dart" },
        { type: "code", text: [
          "import 'package:flutter/material.dart';",
          "",
          "void main() {",
          "  runApp(const MyApp());",
          "}",
          "",
          "class MyApp extends StatelessWidget {",
          "  const MyApp({super.key});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return MaterialApp(",
          "      title: 'My First App',",
          "      theme: ThemeData(primarySwatch: Colors.blue),",
          "      home: const HomePage(),",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "p", text: "`runApp()` takes a widget and makes it the root of the entire widget tree, attaching it to the screen. `MaterialApp` is a convenience widget that sets up Material Design theming, navigation, and localization for the whole app in one place." },
        { type: "h3", text: "Registering Assets" },
        { type: "p", text: "Images, fonts, and other files must be declared in `pubspec.yaml` under `flutter:` before you can use them — Flutter does not scan folders automatically." },
        { type: "code", text: [
          "flutter:",
          "  uses-material-design: true",
          "  assets:",
          "    - assets/images/logo.png",
          "    - assets/data/",
          "  fonts:",
          "    - family: Poppins",
          "      fonts:",
          "        - asset: assets/fonts/Poppins-Regular.ttf",
          "        - asset: assets/fonts/Poppins-Bold.ttf",
          "          weight: 700",
        ].join("\n") },
        { type: "keypoints", items: [
          "`lib/main.dart` is where execution starts; `runApp()` attaches your root widget to the screen.",
          "`MaterialApp` bundles theming, routing, and localization setup for the whole app.",
          "Every asset (image, font, data file) must be explicitly listed in `pubspec.yaml` before use.",
        ]},
      ],
    },

    // ---------------- UNIT 15 ----------------
    {
      number: "15",
      title: "Widgets: The Building Blocks",
      blocks: [
        { type: "p", text: "There are two fundamental categories of widget in Flutter, and choosing the right one for each piece of UI is one of the first real design decisions you'll make in any screen." },
        { type: "h3", text: "StatelessWidget" },
        { type: "p", text: "A `StatelessWidget` describes UI that never changes once built — it has no internal, mutable data. It is rebuilt only when its **parent** passes it new configuration." },
        { type: "code", text: [
          "class Greeting extends StatelessWidget {",
          "  final String name;",
          "  const Greeting({super.key, required this.name});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Text('Hello, $name!');",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "StatefulWidget" },
        { type: "p", text: "A `StatefulWidget` can hold data that changes over time (a counter, a toggled switch, text typed by the user) and rebuild itself whenever that data changes, via `setState()`. Every `StatefulWidget` is paired with a separate `State` object that actually holds the mutable data — the widget itself stays immutable." },
        { type: "code", text: [
          "class Counter extends StatefulWidget {",
          "  const Counter({super.key});",
          "",
          "  @override",
          "  State<Counter> createState() => _CounterState();",
          "}",
          "",
          "class _CounterState extends State<Counter> {",
          "  int _count = 0;",
          "",
          "  void _increment() {",
          "    setState(() {",
          "      _count++;",
          "    });",
          "  }",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Column(",
          "      children: [",
          "        Text('Count: $_count'),",
          "        ElevatedButton(onPressed: _increment, child: const Text('Add')),",
          "      ],",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Never mutate state fields directly (`_count++;` on its own) — Flutter has no way to know the UI needs rebuilding unless the change happens inside `setState()`." },
        { type: "h3", text: "The StatefulWidget Lifecycle" },
        { type: "table", header: ["Method", "Called when"],
          rows: [
            ["`initState()`", "Once, when the State object is first created — good place for one-time setup (subscriptions, controllers)"],
            ["`build()`", "Every time the widget needs to (re)render"],
            ["`didUpdateWidget()`", "When the parent rebuilds this widget with new configuration"],
            ["`setState()`", "Called by your own code to mark state as changed and trigger a rebuild"],
            ["`dispose()`", "Once, when the State object is permanently removed — release controllers, cancel subscriptions here"],
          ]},
        { type: "h3", text: "BuildContext" },
        { type: "p", text: "Every `build()` method receives a `BuildContext` — a handle to the widget's location in the tree. It's used to look up inherited data (theme, media query, navigation) from ancestor widgets, e.g. `Theme.of(context)` or `Navigator.of(context)`." },
        { type: "keypoints", items: [
          "`StatelessWidget` for UI that never changes on its own; `StatefulWidget` for UI with mutable, internal data.",
          "`setState()` is the only correct way to tell Flutter that a `State` object's data changed and the UI needs rebuilding.",
          "`initState()` sets up one-time resources; `dispose()` releases them — always pair the two.",
          "`BuildContext` is how a widget looks upward in the tree for shared data like theme or navigation.",
        ]},
      ],
    },

    // ---------------- UNIT 16 ----------------
    {
      number: "16",
      title: "Core Layout Widgets",
      blocks: [
        { type: "p", text: "Flutter has no CSS — layout is built entirely by nesting widgets. A handful of layout widgets, learned well, cover the vast majority of screens you'll ever build." },
        { type: "h3", text: "Text, Container & Image" },
        { type: "code", text: [
          "Container(",
          "  padding: const EdgeInsets.all(16),",
          "  margin: const EdgeInsets.symmetric(vertical: 8),",
          "  decoration: BoxDecoration(",
          "    color: Colors.blue.shade50,",
          "    borderRadius: BorderRadius.circular(12),",
          "  ),",
          "  child: const Text(",
          "    'Department of AI & DS',",
          "    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Row & Column — the two workhorses" },
        { type: "p", text: "`Row` arranges children horizontally; `Column` arranges children vertically. Both accept `mainAxisAlignment` (alignment along the direction they lay out) and `crossAxisAlignment` (alignment perpendicular to it)." },
        { type: "code", text: [
          "Column(",
          "  mainAxisAlignment: MainAxisAlignment.center,",
          "  crossAxisAlignment: CrossAxisAlignment.start,",
          "  children: [",
          "    const Text('Welcome'),",
          "    const SizedBox(height: 8), // fixed-size spacer",
          "    Row(",
          "      mainAxisAlignment: MainAxisAlignment.spaceBetween,",
          "      children: const [",
          "        Icon(Icons.school),",
          "        Text('LBRCE'),",
          "        Icon(Icons.star),",
          "      ],",
          "    ),",
          "  ],",
          ")",
        ].join("\n") },
        { type: "table", header: ["Widget", "Purpose"],
          rows: [
            ["`Text`", "Display a string with styling"],
            ["`Container`", "A box you can size, pad, color, decorate, and position a single child within"],
            ["`Row` / `Column`", "Arrange children horizontally / vertically"],
            ["`Stack`", "Overlap children on top of one another (for badges, watermarks, layered UI)"],
            ["`Padding`", "Add space around a single child"],
            ["`Center`", "Center a single child within available space"],
            ["`SizedBox`", "A box of a fixed width/height — commonly used purely as a spacer"],
            ["`Image`", "Display an image from assets, network, memory, or file"],
          ]},
        { type: "h3", text: "Stack — Overlapping Widgets" },
        { type: "code", text: [
          "Stack(",
          "  alignment: Alignment.center,",
          "  children: [",
          "    Image.asset('assets/images/banner.png'),",
          "    Positioned(",
          "      bottom: 10,",
          "      right: 10,",
          "      child: Container(",
          "        padding: const EdgeInsets.all(6),",
          "        color: Colors.black54,",
          "        child: const Text('NEW', style: TextStyle(color: Colors.white)),",
          "      ),",
          "    ),",
          "  ],",
          ")",
        ].join("\n") },
        { type: "keypoints", items: [
          "There is no CSS in Flutter — every layout decision is a widget you nest.",
          "`Row`/`Column` plus `mainAxisAlignment`/`crossAxisAlignment` cover most simple layouts.",
          "`Stack` + `Positioned` is how you overlap widgets, e.g. a badge on an icon.",
          "`SizedBox` is the idiomatic way to add fixed empty space between widgets.",
        ]},
      ],
    },

    // ---------------- UNIT 17 ----------------
    {
      number: "17",
      title: "Advanced Layouts & Scrolling",
      blocks: [
        { type: "h3", text: "Expanded & Flexible" },
        { type: "p", text: "Inside a `Row` or `Column`, `Expanded` forces a child to fill the remaining available space; `Flexible` lets a child shrink to fit without necessarily filling all remaining space. The `flex` property distributes space proportionally between multiple `Expanded` children." },
        { type: "code", text: [
          "Row(",
          "  children: [",
          "    Expanded(flex: 2, child: Container(color: Colors.red, height: 50)),",
          "    Expanded(flex: 1, child: Container(color: Colors.green, height: 50)),",
          "  ],",
          ")",
          "// The red box takes twice the width of the green box.",
        ].join("\n") },
        { type: "h3", text: "ListView — scrollable lists" },
        { type: "code", text: [
          "// Fixed list of children",
          "ListView(",
          "  children: const [",
          "    ListTile(leading: Icon(Icons.book), title: Text('Data Structures')),",
          "    ListTile(leading: Icon(Icons.code), title: Text('Flutter Lab')),",
          "  ],",
          ")",
          "",
          "// Efficient for long or dynamic lists — builds items lazily as they scroll into view",
          "ListView.builder(",
          "  itemCount: subjects.length,",
          "  itemBuilder: (context, index) {",
          "    return ListTile(title: Text(subjects[index]));",
          "  },",
          ")",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Always prefer `ListView.builder` over a plain `ListView(children: [...])` once the list can grow large — `.builder` only constructs the widgets currently visible on screen, which is dramatically more memory-efficient." },
        { type: "h3", text: "GridView — grid layouts" },
        { type: "code", text: [
          "GridView.builder(",
          "  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(",
          "    crossAxisCount: 2,",
          "    crossAxisSpacing: 8,",
          "    mainAxisSpacing: 8,",
          "  ),",
          "  itemCount: 6,",
          "  itemBuilder: (context, index) => Card(",
          "    child: Center(child: Text('Item $index')),",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Wrap — flowing layout" },
        { type: "code", text: [
          "Wrap(",
          "  spacing: 8,     // horizontal gap between items",
          "  runSpacing: 8,  // vertical gap between wrapped lines",
          "  children: [",
          "    Chip(label: Text('AI')),",
          "    Chip(label: Text('Data Science')),",
          "    Chip(label: Text('Flutter')),",
          "    Chip(label: Text('IoT')),",
          "  ],",
          ")",
        ].join("\n") },
        { type: "table", header: ["Widget", "Best for"],
          rows: [
            ["`ListView.builder`", "Long or dynamic vertical/horizontal lists"],
            ["`GridView.builder`", "Photo grids, dashboards, card layouts"],
            ["`Wrap`", "Tags/chips that should flow onto multiple lines"],
            ["`SingleChildScrollView`", "A single, possibly-overflowing widget (e.g. a tall form) that needs to scroll"],
          ]},
        { type: "keypoints", items: [
          "`Expanded`/`Flexible` distribute remaining space inside a `Row`/`Column`; `flex` controls the ratio.",
          "`.builder` constructors (`ListView.builder`, `GridView.builder`) are essential for performance once a list can grow large.",
          "`Wrap` is the go-to widget for tag/chip-style content that should flow across lines instead of overflowing.",
        ]},
      ],
    },

    // ---------------- UNIT 18 ----------------
    {
      number: "18",
      title: "User Input, Forms & Buttons",
      blocks: [
        { type: "h3", text: "Buttons" },
        { type: "code", text: [
          "ElevatedButton(",
          "  onPressed: () => print('Submitted'),",
          "  child: const Text('Submit'),",
          ")",
          "",
          "TextButton(onPressed: () {}, child: const Text('Cancel')),",
          "OutlinedButton(onPressed: () {}, child: const Text('Learn More')),",
          "IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),",
        ].join("\n") },
        { type: "h3", text: "TextField — free-form input" },
        { type: "code", text: [
          "final TextEditingController _controller = TextEditingController();",
          "",
          "TextField(",
          "  controller: _controller,",
          "  decoration: const InputDecoration(",
          "    labelText: 'Faculty Name',",
          "    border: OutlineInputBorder(),",
          "  ),",
          "  onChanged: (value) => print('Typing: $value'),",
          ")",
          "",
          "// Reading the value later:",
          "print(_controller.text);",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Always call `_controller.dispose()` inside your `State`'s `dispose()` method — `TextEditingController`s hold resources that must be released when the widget is removed from the tree." },
        { type: "h3", text: "Form & Validation" },
        { type: "code", text: [
          "final _formKey = GlobalKey<FormState>();",
          "",
          "Form(",
          "  key: _formKey,",
          "  child: Column(",
          "    children: [",
          "      TextFormField(",
          "        decoration: const InputDecoration(labelText: 'Email'),",
          "        validator: (value) {",
          "          if (value == null || !value.contains('@')) {",
          "            return 'Enter a valid email';",
          "          }",
          "          return null; // null means \"valid\"",
          "        },",
          "      ),",
          "      ElevatedButton(",
          "        onPressed: () {",
          "          if (_formKey.currentState!.validate()) {",
          "            print('Form is valid — proceed');",
          "          }",
          "        },",
          "        child: const Text('Submit'),",
          "      ),",
          "    ],",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Other Common Input Widgets" },
        { type: "table", header: ["Widget", "Use"],
          rows: [
            ["`Checkbox`", "Boolean on/off, typically paired with a `Text` label"],
            ["`Switch`", "Toggle setting, styled like a mobile switch"],
            ["`Radio`", "Choose one option from a group"],
            ["`DropdownButton`", "Choose one option from a dropdown list"],
            ["`Slider`", "Choose a value from a continuous or stepped numeric range"],
            ["`DatePicker` / `showDatePicker()`", "Native-style date selection dialog"],
          ]},
        { type: "keypoints", items: [
          "`TextEditingController` reads and controls a `TextField`'s content — always dispose it.",
          "`Form` + `TextFormField` + `validator` gives you declarative, per-field validation with a single `validate()` call.",
          "A `validator` returning `null` means the field is valid; any other `String` is shown as the error message.",
        ]},
      ],
    },

    // ---------------- UNIT 19 ----------------
    {
      number: "19",
      title: "Navigation & Routing",
      blocks: [
        { type: "p", text: "Flutter manages screens with a **stack** of routes, managed by the `Navigator` widget — pushing a route shows a new screen on top; popping removes it and reveals what was underneath." },
        { type: "h3", text: "Basic Navigation with push/pop" },
        { type: "code", text: [
          "// Navigate to a new screen",
          "Navigator.push(",
          "  context,",
          "  MaterialPageRoute(builder: (context) => const DetailsPage()),",
          ");",
          "",
          "// Go back to the previous screen",
          "Navigator.pop(context);",
        ].join("\n") },
        { type: "h3", text: "Passing Data Forward" },
        { type: "code", text: [
          "Navigator.push(",
          "  context,",
          "  MaterialPageRoute(",
          "    builder: (context) => DetailsPage(studentName: 'Anita'),",
          "  ),",
          ");",
          "",
          "class DetailsPage extends StatelessWidget {",
          "  final String studentName;",
          "  const DetailsPage({super.key, required this.studentName});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(body: Center(child: Text('Hello, $studentName')));",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Returning Data Backward" },
        { type: "code", text: [
          "// On the calling screen — await the result",
          "final result = await Navigator.push(",
          "  context,",
          "  MaterialPageRoute(builder: (context) => const SelectionPage()),",
          ");",
          "print('User selected: $result');",
          "",
          "// On the SelectionPage — pop with a value",
          "Navigator.pop(context, 'Option A');",
        ].join("\n") },
        { type: "h3", text: "Named Routes" },
        { type: "p", text: "For apps with many screens, named routes centralize navigation in one place instead of importing every page's class everywhere." },
        { type: "code", text: [
          "MaterialApp(",
          "  initialRoute: '/',",
          "  routes: {",
          "    '/': (context) => const HomePage(),",
          "    '/details': (context) => const DetailsPage(),",
          "    '/settings': (context) => const SettingsPage(),",
          "  },",
          ")",
          "",
          "// Navigate using the route name",
          "Navigator.pushNamed(context, '/details');",
        ].join("\n") },
        { type: "note", kind: "tip", text: "For apps with complex, deep-linkable navigation (especially on the web, where URLs matter), consider the `go_router` package — it builds on top of Navigator 2.0 and is the community-standard solution for declarative, URL-based routing." },
        { type: "keypoints", items: [
          "`Navigator.push`/`pop` manipulate a stack of screens; the top of the stack is what's visible.",
          "`await Navigator.push(...)` lets a screen receive a result back once the pushed screen calls `Navigator.pop(context, result)`.",
          "Named routes centralize route definitions in `MaterialApp`, useful once an app has more than a handful of screens.",
        ]},
      ],
    },

    // ---------------- UNIT 20 ----------------
    {
      number: "20",
      title: "State Management",
      blocks: [
        { type: "p", text: "\"State management\" is simply the question: **when data changes, how does the right part of the UI find out and rebuild?** `setState()` (Unit 15) answers this for a single widget's own local state. As an app grows, you need patterns for sharing state *across* widgets that aren't directly related in the tree." },
        { type: "h3", text: "setState() — Local State" },
        { type: "p", text: "Best for state that belongs to, and is only needed by, one widget and its direct children — a single form's validity, whether a card is expanded, an animation's progress." },
        { type: "h3", text: "InheritedWidget — Flutter's Built-in Sharing Mechanism" },
        { type: "p", text: "`InheritedWidget` lets any descendant efficiently read data from an ancestor without it being passed down manually through every constructor (\"prop drilling\"). Most higher-level state management packages (including `Provider`) are built on top of this primitive." },
        { type: "h3", text: "Provider — the recommended starting point" },
        { type: "p", text: "`provider` is the package the Flutter team itself recommends for small-to-medium apps. It wraps `InheritedWidget` in a much friendlier API." },
        { type: "code", text: [
          "// 1. Define your state as a ChangeNotifier",
          "class CounterModel extends ChangeNotifier {",
          "  int _count = 0;",
          "  int get count => _count;",
          "",
          "  void increment() {",
          "    _count++;",
          "    notifyListeners(); // tells every listening widget to rebuild",
          "  }",
          "}",
          "",
          "// 2. Provide it above the widgets that need it",
          "void main() {",
          "  runApp(",
          "    ChangeNotifierProvider(",
          "      create: (context) => CounterModel(),",
          "      child: const MyApp(),",
          "    ),",
          "  );",
          "}",
          "",
          "// 3. Consume it anywhere below",
          "class CounterDisplay extends StatelessWidget {",
          "  const CounterDisplay({super.key});",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    final count = context.watch<CounterModel>().count;",
          "    return Text('Count: $count');",
          "  }",
          "}",
          "",
          "class IncrementButton extends StatelessWidget {",
          "  const IncrementButton({super.key});",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return ElevatedButton(",
          "      onPressed: () => context.read<CounterModel>().increment(),",
          "      child: const Text('+1'),",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`context.watch<T>()` subscribes the widget to rebuilds whenever `T` calls `notifyListeners()`. `context.read<T>()` grabs the value once, without subscribing — use it inside callbacks like `onPressed` where you don't want a rebuild every time you merely read the value." },
        { type: "h3", text: "Riverpod — Provider's Compile-Safe Successor" },
        { type: "p", text: "Riverpod keeps Provider's core idea but removes its two biggest pain points: providers no longer need a `BuildContext` to be read (so they work in plain Dart, not just widgets), and mismatched provider types are caught by the compiler instead of at runtime." },
        { type: "code", text: [
          "// 1. Declare a provider at the top level of a file",
          "final counterProvider = StateNotifierProvider<CounterNotifier, int>(",
          "  (ref) => CounterNotifier(),",
          ");",
          "",
          "class CounterNotifier extends StateNotifier<int> {",
          "  CounterNotifier() : super(0);",
          "  void increment() => state = state + 1;",
          "}",
          "",
          "// 2. Wrap the app in a ProviderScope (instead of ChangeNotifierProvider)",
          "void main() {",
          "  runApp(const ProviderScope(child: MyApp()));",
          "}",
          "",
          "// 3. Consume with a ConsumerWidget instead of StatelessWidget",
          "class CounterDisplay extends ConsumerWidget {",
          "  const CounterDisplay({super.key});",
          "  @override",
          "  Widget build(BuildContext context, WidgetRef ref) {",
          "    final count = ref.watch(counterProvider);",
          "    return Text('Count: $count');",
          "  }",
          "}",
          "",
          "class IncrementButton extends ConsumerWidget {",
          "  const IncrementButton({super.key});",
          "  @override",
          "  Widget build(BuildContext context, WidgetRef ref) {",
          "    return ElevatedButton(",
          "      onPressed: () => ref.read(counterProvider.notifier).increment(),",
          "      child: const Text('+1'),",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Bloc — Strict, Event-Driven State Management" },
        { type: "p", text: "Bloc formalizes state changes as a stream of **events in, states out** — every state change must be traceable to an explicit event, which makes very large apps with many contributors easier to reason about and test, at the cost of more upfront boilerplate." },
        { type: "code", text: [
          "// Events — what can happen",
          "abstract class CounterEvent {}",
          "class IncrementPressed extends CounterEvent {}",
          "",
          "// The Bloc — maps events to new states",
          "class CounterBloc extends Bloc<CounterEvent, int> {",
          "  CounterBloc() : super(0) {",
          "    on<IncrementPressed>((event, emit) => emit(state + 1));",
          "  }",
          "}",
          "",
          "// Providing it, using flutter_bloc's BlocProvider",
          "BlocProvider(",
          "  create: (context) => CounterBloc(),",
          "  child: const CounterScreen(),",
          ")",
          "",
          "// Consuming it with BlocBuilder",
          "BlocBuilder<CounterBloc, int>(",
          "  builder: (context, count) => Text('Count: $count'),",
          ")",
          "",
          "// Firing an event",
          "context.read<CounterBloc>().add(IncrementPressed());",
        ].join("\n") },
        { type: "h3", text: "Choosing Between Them" },
        { type: "table", header: ["Approach", "Good fit for", "Trade-off"],
          rows: [
            ["`setState`", "Small, single-widget-local state", "Doesn't scale to sharing state across screens"],
            ["`Provider`", "Small-to-medium apps; official recommendation for most projects", "Runtime type lookups; easy to misuse `watch` vs `read`"],
            ["`Riverpod`", "Same range as Provider, plus apps wanting compile-time safety and testability outside widgets", "Slightly steeper learning curve than Provider"],
            ["`Bloc` / `flutter_bloc`", "Large teams/apps wanting a strict, event-driven, highly testable architecture", "More boilerplate per feature (events + states + bloc)"],
            ["`GetX`", "Rapid development with state management, routing, and DI combined", "Less idiomatic Flutter; more \"magic\" than the alternatives above"],
          ]},
        { type: "keypoints", items: [
          "State management answers one question: how does a UI change get communicated to everything that depends on it?",
          "`ChangeNotifier` + `notifyListeners()` + `Provider` is the most common beginner-to-intermediate pattern in real Flutter apps.",
          "`context.watch<T>()` rebuilds on change; `context.read<T>()` reads once without subscribing — using the wrong one is a very common source of bugs.",
        ]},
      ],
    },

    // ---------------- UNIT 21 ----------------
    {
      number: "21",
      title: "Networking & REST APIs",
      blocks: [
        { type: "p", text: "The `http` package (published by the Dart team) is the standard, lightweight way to make network requests. Add it to `pubspec.yaml` (`http: ^1.2.0`) and run `flutter pub get` before using it." },
        { type: "h3", text: "Making a GET Request" },
        { type: "code", text: [
          "import 'dart:convert';",
          "import 'package:http/http.dart' as http;",
          "",
          "Future<List<dynamic>> fetchStudents() async {",
          "  final response = await http.get(",
          "    Uri.parse('https://api.example.com/students'),",
          "  );",
          "",
          "  if (response.statusCode == 200) {",
          "    return jsonDecode(response.body) as List<dynamic>;",
          "  } else {",
          "    throw Exception('Failed to load students: ${response.statusCode}');",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Modeling JSON with a Class" },
        { type: "p", text: "Rather than passing raw `Map<String, dynamic>` objects around, define a model class with a `fromJson` factory constructor — this keeps parsing logic in one place and gives you compile-time type safety everywhere else." },
        { type: "code", text: [
          "class Student {",
          "  final String name;",
          "  final int rollNumber;",
          "",
          "  Student({required this.name, required this.rollNumber});",
          "",
          "  factory Student.fromJson(Map<String, dynamic> json) {",
          "    return Student(",
          "      name: json['name'] as String,",
          "      rollNumber: json['rollNumber'] as int,",
          "    );",
          "  }",
          "}",
          "",
          "Future<List<Student>> fetchStudents() async {",
          "  final response = await http.get(Uri.parse('https://api.example.com/students'));",
          "  final List<dynamic> jsonList = jsonDecode(response.body);",
          "  return jsonList.map((json) => Student.fromJson(json)).toList();",
          "}",
        ].join("\n") },
        { type: "h3", text: "Displaying Async Data with FutureBuilder" },
        { type: "code", text: [
          "FutureBuilder<List<Student>>(",
          "  future: fetchStudents(),",
          "  builder: (context, snapshot) {",
          "    if (snapshot.connectionState == ConnectionState.waiting) {",
          "      return const CircularProgressIndicator();",
          "    } else if (snapshot.hasError) {",
          "      return Text('Error: ${snapshot.error}');",
          "    } else {",
          "      final students = snapshot.data!;",
          "      return ListView.builder(",
          "        itemCount: students.length,",
          "        itemBuilder: (context, i) => ListTile(title: Text(students[i].name)),",
          "      );",
          "    }",
          "  },",
          ")",
        ].join("\n") },
        { type: "note", kind: "tip", text: "`FutureBuilder` rebuilds automatically as its `future` moves through waiting → data/error states — you never need to manually call `setState()` just to show a loading spinner." },
        { type: "h3", text: "POST Request Example" },
        { type: "code", text: [
          "Future<void> createStudent(String name, int roll) async {",
          "  final response = await http.post(",
          "    Uri.parse('https://api.example.com/students'),",
          "    headers: {'Content-Type': 'application/json'},",
          "    body: jsonEncode({'name': name, 'rollNumber': roll}),",
          "  );",
          "  if (response.statusCode != 201) {",
          "    throw Exception('Failed to create student');",
          "  }",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "The `http` package handles GET/POST/PUT/DELETE requests; `dart:convert`'s `jsonDecode`/`jsonEncode` handle JSON parsing.",
          "A `fromJson` factory constructor on a model class centralizes parsing and gives the rest of your app type safety.",
          "`FutureBuilder` is the idiomatic Flutter widget for rendering loading/data/error states from a single `Future`.",
        ]},
      ],
    },

    // ---------------- UNIT 22 ----------------
    {
      number: "22",
      title: "Local Data Persistence",
      blocks: [
        { type: "h3", text: "shared_preferences — simple key-value storage" },
        { type: "p", text: "Ideal for small amounts of data: user settings, a login flag, a theme preference. Not suitable for structured or large datasets." },
        { type: "code", text: [
          "import 'package:shared_preferences/shared_preferences.dart';",
          "",
          "Future<void> saveUsername(String name) async {",
          "  final prefs = await SharedPreferences.getInstance();",
          "  await prefs.setString('username', name);",
          "}",
          "",
          "Future<String?> loadUsername() async {",
          "  final prefs = await SharedPreferences.getInstance();",
          "  return prefs.getString('username');",
          "}",
        ].join("\n") },
        { type: "h3", text: "sqflite — local SQL database" },
        { type: "p", text: "For structured, relational, and larger datasets stored entirely on-device, `sqflite` gives you a full local SQLite database." },
        { type: "code", text: [
          "import 'package:sqflite/sqflite.dart';",
          "import 'package:path/path.dart';",
          "",
          "Future<Database> openAppDatabase() async {",
          "  final path = join(await getDatabasesPath(), 'app.db');",
          "  return openDatabase(",
          "    path,",
          "    version: 1,",
          "    onCreate: (db, version) {",
          "      return db.execute(",
          "        'CREATE TABLE students(id INTEGER PRIMARY KEY, name TEXT, roll INTEGER)',",
          "      );",
          "    },",
          "  );",
          "}",
          "",
          "Future<void> insertStudent(Database db, String name, int roll) async {",
          "  await db.insert('students', {'name': name, 'roll': roll});",
          "}",
          "",
          "Future<List<Map<String, dynamic>>> getStudents(Database db) async {",
          "  return db.query('students');",
          "}",
        ].join("\n") },
        { type: "table", header: ["Option", "Best for", "Not ideal for"],
          rows: [
            ["`shared_preferences`", "Flags, small settings, simple strings/numbers/bools", "Structured or relational data"],
            ["`sqflite`", "Relational, queryable, larger local datasets", "Simple one-off flags (overkill)"],
            ["`hive`", "Fast, NoSQL, no native SQL knowledge required", "Complex relational queries across tables"],
          ]},
        { type: "keypoints", items: [
          "`shared_preferences` is for small, simple key-value data; it is not a database.",
          "`sqflite` gives full local SQL capability when your data is structured and relational.",
          "All persistence operations are asynchronous — always `await` them.",
        ]},
      ],
    },

    // ---------------- UNIT 23 ----------------
    {
      number: "23",
      title: "Animations",
      blocks: [
        { type: "h3", text: "Implicit Animations — the easy 80%" },
        { type: "p", text: "Widgets prefixed `Animated*` handle the entire animation for you — just change a property, and the widget smoothly animates from the old value to the new one." },
        { type: "code", text: [
          "class FadeBox extends StatefulWidget {",
          "  const FadeBox({super.key});",
          "  @override",
          "  State<FadeBox> createState() => _FadeBoxState();",
          "}",
          "",
          "class _FadeBoxState extends State<FadeBox> {",
          "  double _opacity = 1.0;",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return GestureDetector(",
          "      onTap: () => setState(() => _opacity = _opacity == 1.0 ? 0.2 : 1.0),",
          "      child: AnimatedOpacity(",
          "        opacity: _opacity,",
          "        duration: const Duration(milliseconds: 400),",
          "        child: Container(width: 100, height: 100, color: Colors.teal),",
          "      ),",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "table", header: ["Widget", "Animates"],
          rows: [
            ["`AnimatedOpacity`", "Fade in/out"],
            ["`AnimatedContainer`", "Size, color, padding, decoration — all at once"],
            ["`AnimatedAlign`", "Position within a parent"],
            ["`AnimatedCrossFade`", "Cross-fade between two entirely different widgets"],
          ]},
        { type: "h3", text: "Explicit Animations — full control" },
        { type: "p", text: "When you need precise control (looping, reversing, chaining multiple properties together), use an `AnimationController` directly. It requires a `TickerProvider`, which is why the `State` class mixes in `SingleTickerProviderStateMixin`." },
        { type: "code", text: [
          "class PulsingIcon extends StatefulWidget {",
          "  const PulsingIcon({super.key});",
          "  @override",
          "  State<PulsingIcon> createState() => _PulsingIconState();",
          "}",
          "",
          "class _PulsingIconState extends State<PulsingIcon>",
          "    with SingleTickerProviderStateMixin {",
          "  late AnimationController _controller;",
          "  late Animation<double> _scale;",
          "",
          "  @override",
          "  void initState() {",
          "    super.initState();",
          "    _controller = AnimationController(",
          "      vsync: this,",
          "      duration: const Duration(seconds: 1),",
          "    )..repeat(reverse: true);",
          "    _scale = Tween<double>(begin: 0.8, end: 1.2).animate(_controller);",
          "  }",
          "",
          "  @override",
          "  void dispose() {",
          "    _controller.dispose();",
          "    super.dispose();",
          "  }",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return ScaleTransition(scale: _scale, child: const Icon(Icons.favorite, size: 48));",
          "  }",
          "}",
        ].join("\n") },
        { type: "note", kind: "warning", text: "Every `AnimationController` you create must be disposed in `dispose()`. A forgotten controller keeps ticking in the background after its widget is gone, wasting resources and, in some cases, causing errors when it eventually calls `setState()` on an unmounted widget." },
        { type: "keypoints", items: [
          "`Animated*` widgets cover simple property-change animations with almost no boilerplate.",
          "`AnimationController` + `Tween` gives full control for loops, reversals, and custom curves.",
          "Always dispose an `AnimationController` in the `State`'s `dispose()` method.",
        ]},
      ],
    },

    // ---------------- UNIT 24 ----------------
    {
      number: "24",
      title: "Theming & Styling",
      blocks: [
        { type: "p", text: "Rather than styling every widget individually, define a single `ThemeData` and let every Material widget in the app inherit from it — this is what makes rebranding an app (or supporting dark mode) a matter of editing one object instead of hundreds of widgets." },
        { type: "code", text: [
          "MaterialApp(",
          "  theme: ThemeData(",
          "    colorScheme: ColorScheme.fromSeed(seedColor: Colors.indigo),",
          "    fontFamily: 'Poppins',",
          "    appBarTheme: const AppBarTheme(centerTitle: true, elevation: 2),",
          "    elevatedButtonTheme: ElevatedButtonThemeData(",
          "      style: ElevatedButton.styleFrom(",
          "        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),",
          "        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),",
          "      ),",
          "    ),",
          "  ),",
          "  darkTheme: ThemeData.dark(),",
          "  themeMode: ThemeMode.system, // follows the device's light/dark setting",
          "  home: const HomePage(),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Reading Theme Values Inside a Widget" },
        { type: "code", text: [
          "Widget build(BuildContext context) {",
          "  final theme = Theme.of(context);",
          "  return Text(",
          "    'Quarterly Report',",
          "    style: theme.textTheme.headlineSmall,",
          "  );",
          "}",
        ].join("\n") },
        { type: "h3", text: "Material vs Cupertino" },
        { type: "p", text: "Flutter ships two complete design systems out of the box: **Material** (`package:flutter/material.dart`), Google's design language used across Android and the web, and **Cupertino** (`package:flutter/cupertino.dart`), which mimics Apple's iOS design language. Most cross-platform apps use Material everywhere for consistency, reserving Cupertino widgets for apps that specifically want an iOS-native look and feel." },
        { type: "keypoints", items: [
          "`ThemeData` centralizes colors, fonts, and component styles for the entire app.",
          "`Theme.of(context)` reads the active theme from anywhere in the widget tree.",
          "`ThemeMode.system` automatically switches between `theme` and `darkTheme` based on the device setting.",
        ]},
      ],
    },

    // ---------------- UNIT 25 ----------------
    {
      number: "25",
      title: "Gestures & Interactivity",
      blocks: [
        { type: "p", text: "Flutter widgets like `ElevatedButton` handle taps for you, but for custom interactive UI (a tappable card, a swipeable item, a draggable widget) you reach for gesture-detection widgets directly." },
        { type: "h3", text: "GestureDetector" },
        { type: "code", text: [
          "GestureDetector(",
          "  onTap: () => print('Tapped'),",
          "  onDoubleTap: () => print('Double tapped'),",
          "  onLongPress: () => print('Long pressed'),",
          "  onPanUpdate: (details) => print('Dragged: ${details.delta}'),",
          "  child: Container(",
          "    width: 120,",
          "    height: 120,",
          "    color: Colors.orange,",
          "    child: const Center(child: Text('Tap Me')),",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "InkWell — Material tap feedback" },
        { type: "p", text: "`InkWell` behaves like `GestureDetector` for taps, but also draws Material Design's signature ripple effect — use it instead of `GestureDetector` whenever the tappable area sits on top of a Material surface (like a `Card` or `Container` with a solid color)." },
        { type: "code", text: [
          "Material(",
          "  color: Colors.blue.shade50,",
          "  child: InkWell(",
          "    onTap: () => print('Card tapped'),",
          "    borderRadius: BorderRadius.circular(8),",
          "    child: const Padding(",
          "      padding: EdgeInsets.all(16),",
          "      child: Text('Tap this card'),",
          "    ),",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Dismissible — swipe-to-delete" },
        { type: "code", text: [
          "Dismissible(",
          "  key: Key(item.id),",
          "  direction: DismissDirection.endToStart,",
          "  onDismissed: (direction) {",
          "    setState(() => items.remove(item));",
          "  },",
          "  background: Container(color: Colors.red),",
          "  child: ListTile(title: Text(item.name)),",
          ")",
        ].join("\n") },
        { type: "keypoints", items: [
          "`GestureDetector` is the general-purpose widget for taps, drags, and long-presses.",
          "`InkWell` adds the Material ripple effect and should be preferred on Material surfaces.",
          "`Dismissible` gives you swipe-to-remove behaviour with almost no manual gesture math.",
        ]},
      ],
    },

    // ---------------- UNIT 26 ----------------
    {
      number: "26",
      title: "Testing in Flutter",
      blocks: [
        { type: "p", text: "Flutter's testing story spans three levels, and the `flutter_test` package (included by default) covers the first two out of the box." },
        { type: "table", header: ["Test type", "What it checks", "Speed"],
          rows: [
            ["Unit test", "A single function or class, in isolation, no UI", "Fastest"],
            ["Widget test", "A single widget's UI and behaviour, in a simulated environment", "Fast"],
            ["Integration test", "The full app running on a real device/emulator, end to end", "Slowest, most realistic"],
          ]},
        { type: "h3", text: "Unit Test Example" },
        { type: "code", text: [
          "// lib/calculator.dart",
          "int add(int a, int b) => a + b;",
          "",
          "// test/calculator_test.dart",
          "import 'package:flutter_test/flutter_test.dart';",
          "import 'package:my_app/calculator.dart';",
          "",
          "void main() {",
          "  test('add() sums two integers correctly', () {",
          "    expect(add(2, 3), 5);",
          "  });",
          "}",
        ].join("\n") },
        { type: "h3", text: "Widget Test Example" },
        { type: "code", text: [
          "import 'package:flutter/material.dart';",
          "import 'package:flutter_test/flutter_test.dart';",
          "import 'package:my_app/counter.dart';",
          "",
          "void main() {",
          "  testWidgets('Counter increments when button is tapped', (tester) async {",
          "    await tester.pumpWidget(const MaterialApp(home: Counter()));",
          "",
          "    expect(find.text('Count: 0'), findsOneWidget);",
          "",
          "    await tester.tap(find.text('Add'));",
          "    await tester.pump(); // rebuild the widget tree after the state change",
          "",
          "    expect(find.text('Count: 1'), findsOneWidget);",
          "  });",
          "}",
        ].join("\n") },
        { type: "p", text: "Run all tests with:" },
        { type: "code", text: "flutter test" },
        { type: "keypoints", items: [
          "Unit tests check pure logic; widget tests check a widget's rendering and interaction; integration tests check the whole app on a real device.",
          "`tester.pump()` must be called after any action that triggers `setState()`, so the test framework rebuilds the widget tree before you assert on it.",
          "`find.text(...)`, `find.byType(...)`, and `find.byKey(...)` are the main ways widget tests locate elements to interact with or assert on.",
        ]},
      ],
    },

    // ---------------- UNIT 27 ----------------
    {
      number: "27",
      title: "Building, Debugging & Deployment",
      blocks: [
        { type: "h3", text: "Debug vs Profile vs Release Builds" },
        { type: "table", header: ["Mode", "Purpose", "Command"],
          rows: [
            ["Debug", "Development — hot reload, assertions enabled, unoptimized", "`flutter run`"],
            ["Profile", "Performance analysis, close to release speed but with profiling hooks", "`flutter run --profile`"],
            ["Release", "What you ship to users — fully optimized, assertions stripped", "`flutter run --release`"],
          ]},
        { type: "h3", text: "Building an Android APK / App Bundle" },
        { type: "code", text: [
          "# A single APK, useful for direct distribution/testing",
          "flutter build apk --release",
          "",
          "# An App Bundle — the required format for Play Store submission",
          "flutter build appbundle --release",
        ].join("\n") },
        { type: "h3", text: "Building for iOS" },
        { type: "code", text: [
          "flutter build ios --release",
          "# Then open ios/Runner.xcworkspace in Xcode to archive and upload to App Store Connect",
        ].join("\n") },
        { type: "h3", text: "Debugging Tools" },
        { type: "ul", items: [
          "**Flutter DevTools** — a suite of performance, layout, and memory-profiling tools accessible via a browser link printed when you run `flutter run`.",
          "**Widget Inspector** — visually select any widget on screen and see its full properties and position in the tree.",
          "**`debugPrint()`** — like `print()`, but automatically avoids truncating very long output, which plain `print()` can do on some platforms.",
          "**`flutter analyze`** — runs Dart's static analyzer across your project to catch type errors, unused imports, and lint issues before you even run the app.",
        ]},
        { type: "note", kind: "tip", text: "Keep `flutter analyze` clean as you go rather than fixing a huge pile of warnings at the end — most Dart/Flutter errors caught this way would otherwise only surface as confusing runtime crashes." },
        { type: "keypoints", items: [
          "Debug mode is for development; always measure performance in profile mode; always ship release mode.",
          "Android apps are packaged as an APK (direct install) or App Bundle (Play Store, the required modern format).",
          "Flutter DevTools and the Widget Inspector are the primary tools for diagnosing layout and performance issues visually.",
        ]},
      ],
    },
  ],
};
