module.exports = {
  units: [
    // ---------------- CUSTOM WIDGETS & COMPOSITION ----------------
    {
      number: "x",
      title: "Custom Widgets & Composition",
      blocks: [
        { type: "p", text: "Flutter's guiding philosophy is **composition over configuration** — instead of one giant, deeply-configurable widget, you build small, focused widgets and combine them. Extracting a repeated chunk of UI into its own widget class is the single most impactful habit for keeping a Flutter codebase readable as it grows." },
        { type: "h3", text: "Extracting a Reusable Widget" },
        { type: "code", text: [
          "class StatCard extends StatelessWidget {",
          "  final String label;",
          "  final String value;",
          "  final IconData icon;",
          "",
          "  const StatCard({",
          "    super.key,",
          "    required this.label,",
          "    required this.value,",
          "    required this.icon,",
          "  });",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Card(",
          "      child: Padding(",
          "        padding: const EdgeInsets.all(16),",
          "        child: Row(",
          "          children: [",
          "            Icon(icon, size: 32, color: Theme.of(context).primaryColor),",
          "            const SizedBox(width: 12),",
          "            Column(",
          "              crossAxisAlignment: CrossAxisAlignment.start,",
          "              children: [",
          "                Text(value, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),",
          "                Text(label, style: const TextStyle(color: Colors.grey)),",
          "              ],",
          "            ),",
          "          ],",
          "        ),",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
          "// Reused anywhere, with different data:",
          "const StatCard(label: 'Papers Published', value: '118', icon: Icons.article)",
        ].join("\n") },
        { type: "note", kind: "tip", text: "A common rule of thumb: if a `build()` method exceeds roughly 60-80 lines, or the same widget subtree appears more than once, it's usually time to extract a new widget class rather than a helper method that merely returns a `Widget` — real widget classes give Flutter's diffing algorithm useful information that helper methods don't." },
        { type: "h3", text: "Composing with `child` and `children`" },
        { type: "p", text: "Accepting a `Widget child` (or `List<Widget> children`) parameter, rather than hard-coding content, is what makes your own widgets as flexible as Flutter's built-in ones." },
        { type: "code", text: [
          "class RoundedPanel extends StatelessWidget {",
          "  final Widget child;",
          "  const RoundedPanel({super.key, required this.child});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Container(",
          "      padding: const EdgeInsets.all(16),",
          "      decoration: BoxDecoration(",
          "        color: Colors.white,",
          "        borderRadius: BorderRadius.circular(12),",
          "        boxShadow: [BoxShadow(color: Colors.black12, blurRadius: 8)],",
          "      ),",
          "      child: child,",
          "    );",
          "  }",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "Extract a widget class, not just a method, whenever UI is reused or a `build()` method grows large.",
          "Accepting `child`/`children` parameters is what makes a custom widget composable rather than a rigid, one-off template.",
          "Composition is the core Flutter design pattern — nearly every built-in widget is itself built by composing smaller ones.",
        ]},
      ],
    },

    // ---------------- SLIVERS ----------------
    {
      number: "x",
      title: "Slivers & CustomScrollView",
      blocks: [
        { type: "p", text: "A **sliver** is a portion of a scrollable area that Flutter can lay out, paint, and clip lazily — the low-level mechanism behind every scrolling widget you've already used, including `ListView`. Working with slivers directly becomes necessary once a screen needs to mix several *different kinds* of scrolling content in one continuous scroll — for example, a collapsing header image above a list." },
        { type: "h3", text: "CustomScrollView with SliverAppBar" },
        { type: "code", text: [
          "CustomScrollView(",
          "  slivers: [",
          "    SliverAppBar(",
          "      expandedHeight: 200,",
          "      pinned: true,",
          "      flexibleSpace: FlexibleSpaceBar(",
          "        title: const Text('AI & DS Department'),",
          "        background: Image.asset('assets/images/banner.png', fit: BoxFit.cover),",
          "      ),",
          "    ),",
          "    SliverList(",
          "      delegate: SliverChildBuilderDelegate(",
          "        (context, index) => ListTile(title: Text('Item $index')),",
          "        childCount: 20,",
          "      ),",
          "    ),",
          "    SliverGrid(",
          "      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),",
          "      delegate: SliverChildBuilderDelegate(",
          "        (context, index) => Card(child: Center(child: Text('Grid $index'))),",
          "        childCount: 6,",
          "      ),",
          "    ),",
          "  ],",
          ")",
        ].join("\n") },
        { type: "note", kind: "tip", text: "As soon as you need a scroll effect that a plain `ListView` or `Column` can't express — a header that shrinks as you scroll, mixed list-and-grid sections, sticky section titles — reach for `CustomScrollView` and its `Sliver*` children instead of nesting scrollables inside each other, which Flutter does not support well." },
        { type: "keypoints", items: [
          "Slivers are the lazy-layout primitive underneath every Flutter scrolling widget.",
          "`CustomScrollView` lets you combine `SliverAppBar`, `SliverList`, and `SliverGrid` into one continuous, coordinated scroll.",
          "Reach for slivers specifically when a screen needs scroll effects beyond what `ListView`/`Column` alone can express.",
        ]},
      ],
    },

    // ---------------- CUSTOM PAINTING ----------------
    {
      number: "x",
      title: "Custom Painting with CustomPainter",
      blocks: [
        { type: "p", text: "For UI that isn't made of standard shapes — custom charts, signature pads, progress rings, hand-drawn diagrams — Flutter exposes the same low-level `Canvas` API its own widgets are built on, via `CustomPainter`." },
        { type: "code", text: [
          "class CirclePainter extends CustomPainter {",
          "  final double progress; // 0.0 to 1.0",
          "  CirclePainter(this.progress);",
          "",
          "  @override",
          "  void paint(Canvas canvas, Size size) {",
          "    final center = Offset(size.width / 2, size.height / 2);",
          "    final radius = size.width / 2;",
          "",
          "    final backgroundPaint = Paint()",
          "      ..color = Colors.grey.shade300",
          "      ..style = PaintingStyle.stroke",
          "      ..strokeWidth = 8;",
          "    canvas.drawCircle(center, radius, backgroundPaint);",
          "",
          "    final progressPaint = Paint()",
          "      ..color = Colors.indigo",
          "      ..style = PaintingStyle.stroke",
          "      ..strokeWidth = 8",
          "      ..strokeCap = StrokeCap.round;",
          "    canvas.drawArc(",
          "      Rect.fromCircle(center: center, radius: radius),",
          "      -3.14159 / 2,           // start at the top",
          "      2 * 3.14159 * progress, // sweep angle based on progress",
          "      false,",
          "      progressPaint,",
          "    );",
          "  }",
          "",
          "  @override",
          "  bool shouldRepaint(CirclePainter oldDelegate) => oldDelegate.progress != progress;",
          "}",
          "",
          "// Usage:",
          "CustomPaint(size: const Size(100, 100), painter: CirclePainter(0.7))",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Always implement `shouldRepaint` deliberately — returning `true` unconditionally forces a repaint on every frame regardless of whether anything actually changed, which is wasteful for anything animated or frequently rebuilt." },
        { type: "keypoints", items: [
          "`CustomPainter` gives direct `Canvas` access for shapes, charts, and effects no built-in widget provides.",
          "`shouldRepaint` controls whether an expensive repaint actually happens — return `false` when the painted output hasn't changed.",
          "Wrap a `CustomPainter` in the `CustomPaint` widget, giving it an explicit `size` when it has no child to size itself by.",
        ]},
      ],
    },

    // ---------------- RESPONSIVE DESIGN ----------------
    {
      number: "x",
      title: "Responsive & Adaptive Design",
      blocks: [
        { type: "p", text: "A Flutter app might run on a phone, a tablet, a foldable, or a desktop window of any size — good layouts adapt rather than assume a fixed screen size. Two tools cover the great majority of real-world responsive needs." },
        { type: "h3", text: "MediaQuery — read the available space" },
        { type: "code", text: [
          "Widget build(BuildContext context) {",
          "  final width = MediaQuery.of(context).size.width;",
          "  final isTablet = width > 600;",
          "",
          "  return isTablet",
          "      ? const TwoColumnLayout()",
          "      : const SingleColumnLayout();",
          "}",
        ].join("\n") },
        { type: "h3", text: "LayoutBuilder — react to the parent's constraints" },
        { type: "p", text: "`MediaQuery` reports the whole screen's size; `LayoutBuilder` reports the space actually available to *this* widget from its parent — the more correct choice when building a reusable widget that might be placed inside a sidebar, a dialog, or a full screen." },
        { type: "code", text: [
          "LayoutBuilder(",
          "  builder: (context, constraints) {",
          "    if (constraints.maxWidth > 600) {",
          "      return const GridView.count(crossAxisCount: 3, children: []);",
          "    } else {",
          "      return const GridView.count(crossAxisCount: 1, children: []);",
          "    }",
          "  },",
          ")",
        ].join("\n") },
        { type: "table", header: ["Tool", "Reports", "Use when"],
          rows: [
            ["`MediaQuery.of(context)`", "The full screen/window size, orientation, padding (e.g. notches)", "Deciding overall app layout, text scaling, safe areas"],
            ["`LayoutBuilder`", "The constraints handed down from this widget's immediate parent", "Building a self-contained, reusable widget that adapts regardless of where it's placed"],
          ]},
        { type: "keypoints", items: [
          "`MediaQuery` gives screen-level information; `LayoutBuilder` gives parent-level constraints — use the one that matches the actual question you're asking.",
          "A common breakpoint convention: under ~600 logical pixels wide = phone layout, 600–900 = tablet, above 900 = desktop/large tablet — adjust to your app's actual content.",
          "Design layouts to respond to available space rather than hard-coding pixel values, so the same codebase looks correct across phones, tablets, and desktop windows.",
        ]},
      ],
    },

    // ---------------- ACCESSIBILITY ----------------
    {
      number: "x",
      title: "Accessibility",
      blocks: [
        { type: "p", text: "Flutter builds a parallel **semantics tree** alongside the widget tree specifically for screen readers (TalkBack on Android, VoiceOver on iOS) and other assistive technology. Most built-in widgets (buttons, text fields, icons with a `tooltip`) already populate reasonable semantics automatically; the `Semantics` widget lets you fill in the gaps for custom widgets." },
        { type: "code", text: [
          "Semantics(",
          "  label: 'Submit quarterly report',",
          "  button: true,",
          "  child: GestureDetector(",
          "    onTap: submitReport,",
          "    child: Container(",
          "      padding: const EdgeInsets.all(12),",
          "      color: Colors.indigo,",
          "      child: const Icon(Icons.send, color: Colors.white),",
          "    ),",
          "  ),",
          ")",
        ].join("\n") },
        { type: "h3", text: "A Practical Accessibility Checklist" },
        { type: "ul", items: [
          "Every tappable `Icon`-only button has either a `tooltip` or an explicit `Semantics(label: ...)`.",
          "Text and background colors meet a reasonable contrast ratio — don't rely on color alone to convey meaning (e.g. red/green status).",
          "Tap targets are at least 48×48 logical pixels, per Material Design guidance.",
          "Text respects the user's device font-scale setting rather than being locked to a fixed pixel size wherever reasonable.",
          "Test the app with TalkBack/VoiceOver turned on at least once before release — issues that are invisible visually are often immediately obvious by ear.",
        ]},
        { type: "keypoints", items: [
          "Flutter maintains a semantics tree specifically for screen readers; most built-in widgets populate it automatically.",
          "Use the `Semantics` widget to describe custom, non-standard widgets that lack an inherent accessible meaning.",
          "Accessibility is a checklist worth reviewing before every release, not a one-time setup step.",
        ]},
      ],
    },

    // ---------------- INTERNATIONALIZATION ----------------
    {
      number: "x",
      title: "Internationalization (i18n & l10n)",
      blocks: [
        { type: "p", text: "Flutter's official internationalization approach uses the `flutter_localizations` SDK package together with `.arb` (Application Resource Bundle) files — one per language — and code generation to produce type-safe access to translated strings." },
        { type: "h3", text: "Setting Up" },
        { type: "code", text: [
          "# pubspec.yaml",
          "dependencies:",
          "  flutter_localizations:",
          "    sdk: flutter",
          "  intl: ^0.19.0",
          "",
          "flutter:",
          "  generate: true",
        ].join("\n") },
        { type: "code", text: [
          "// lib/l10n/app_en.arb",
          "{",
          "  \"helloUser\": \"Hello, {name}!\",",
          "  \"@helloUser\": { \"placeholders\": { \"name\": {} } },",
          "  \"submit\": \"Submit\"",
          "}",
          "",
          "// lib/l10n/app_te.arb (Telugu)",
          "{",
          "  \"helloUser\": \"నమస్కారం, {name}!\",",
          "  \"submit\": \"సమర్పించు\"",
          "}",
        ].join("\n") },
        { type: "code", text: [
          "MaterialApp(",
          "  localizationsDelegates: AppLocalizations.localizationsDelegates,",
          "  supportedLocales: AppLocalizations.supportedLocales,",
          "  home: const HomePage(),",
          ")",
          "",
          "// Anywhere in the widget tree:",
          "Text(AppLocalizations.of(context)!.helloUser('Sudhakar'))",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Run `flutter gen-l10n` (or simply `flutter run`, which triggers it automatically when `generate: true` is set) after editing any `.arb` file to regenerate the type-safe `AppLocalizations` class." },
        { type: "h3", text: "Formatting Dates, Numbers & Currency" },
        { type: "code", text: [
          "import 'package:intl/intl.dart';",
          "",
          "final formattedDate = DateFormat.yMMMMd('en_US').format(DateTime.now());",
          "final formattedCurrency = NumberFormat.currency(locale: 'en_IN', symbol: '₹').format(45000);",
          "print(formattedDate);      // e.g. July 6, 2026",
          "print(formattedCurrency); // ₹45,000.00",
        ].join("\n") },
        { type: "keypoints", items: [
          "`.arb` files hold translated strings per locale; `AppLocalizations` (generated) gives type-safe access to them.",
          "`intl`'s `DateFormat`/`NumberFormat` handle locale-aware formatting far more correctly than manual string building.",
          "Localization should be planned early — retrofitting hard-coded strings across a large, finished app is far more work than starting with `AppLocalizations` in place.",
        ]},
      ],
    },

    // ---------------- PLATFORM CHANNELS ----------------
    {
      number: "x",
      title: "Platform Channels — Talking to Native Code",
      blocks: [
        { type: "p", text: "When a feature genuinely isn't available through any Flutter package — a proprietary native SDK, a very device-specific API — **platform channels** let Dart code call into native Android (Kotlin/Java) or iOS (Swift/Objective-C) code, and receive a result back, asynchronously." },
        { type: "h3", text: "Dart Side" },
        { type: "code", text: [
          "import 'package:flutter/services.dart';",
          "",
          "const platform = MethodChannel('com.lbrce.aids/battery');",
          "",
          "Future<int> getBatteryLevel() async {",
          "  try {",
          "    final int result = await platform.invokeMethod('getBatteryLevel');",
          "    return result;",
          "  } on PlatformException catch (e) {",
          "    print('Failed to get battery level: ${e.message}');",
          "    return -1;",
          "  }",
          "}",
        ].join("\n") },
        { type: "h3", text: "Android Side (Kotlin, simplified)" },
        { type: "code", text: [
          "// android/app/src/main/kotlin/.../MainActivity.kt",
          "MethodChannel(flutterEngine.dartExecutor.binaryMessenger, \"com.lbrce.aids/battery\")",
          "    .setMethodCallHandler { call, result ->",
          "        if (call.method == \"getBatteryLevel\") {",
          "            val level = getBatteryLevelNative()",
          "            result.success(level)",
          "        } else {",
          "            result.notImplemented()",
          "        }",
          "    }",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Before reaching for a custom platform channel, search pub.dev thoroughly — the vast majority of native functionality (battery, sensors, camera, biometrics, connectivity) already has a well-maintained plugin wrapping the platform channel for you." },
        { type: "keypoints", items: [
          "Platform channels are the bridge between Dart and native Android/iOS code, used only when no existing plugin covers the need.",
          "`MethodChannel` sends a named method call with arguments and awaits a single result — conceptually similar to a `Future`-based RPC.",
          "Most plugins on pub.dev (camera, sensors, notifications, etc.) are themselves built on top of platform channels.",
        ]},
      ],
    },

    // ---------------- FIREBASE ----------------
    {
      number: "x",
      title: "Firebase Integration Overview",
      blocks: [
        { type: "p", text: "Firebase is Google's mobile/web backend-as-a-service platform, and it integrates with Flutter through officially maintained plugins (`firebase_core` plus one package per product). It's a common choice for adding authentication, a real-time database, and push notifications without standing up custom backend infrastructure." },
        { type: "h3", text: "Initial Setup" },
        { type: "code", text: [
          "// pubspec.yaml",
          "dependencies:",
          "  firebase_core: ^3.0.0",
          "  cloud_firestore: ^5.0.0",
          "  firebase_auth: ^5.0.0",
        ].join("\n") },
        { type: "code", text: [
          "void main() async {",
          "  WidgetsFlutterBinding.ensureInitialized();",
          "  await Firebase.initializeApp();",
          "  runApp(const MyApp());",
          "}",
        ].join("\n") },
        { type: "h3", text: "Firebase Authentication" },
        { type: "code", text: [
          "import 'package:firebase_auth/firebase_auth.dart';",
          "",
          "Future<User?> signIn(String email, String password) async {",
          "  final credential = await FirebaseAuth.instance",
          "      .signInWithEmailAndPassword(email: email, password: password);",
          "  return credential.user;",
          "}",
        ].join("\n") },
        { type: "h3", text: "Cloud Firestore — reading & writing data" },
        { type: "code", text: [
          "import 'package:cloud_firestore/cloud_firestore.dart';",
          "",
          "Future<void> addStudent(String name, int roll) async {",
          "  await FirebaseFirestore.instance.collection('students').add({",
          "    'name': name,",
          "    'rollNumber': roll,",
          "    'createdAt': FieldValue.serverTimestamp(),",
          "  });",
          "}",
          "",
          "// Live-updating stream of data — pairs naturally with StreamBuilder",
          "Stream<QuerySnapshot> studentsStream() {",
          "  return FirebaseFirestore.instance.collection('students').snapshots();",
          "}",
        ].join("\n") },
        { type: "note", kind: "tip", text: "Firestore's `.snapshots()` returns a `Stream` that emits every time the underlying data changes — combine it directly with `StreamBuilder` (Unit 21) to build UI that updates in real time with no manual polling or refresh logic." },
        { type: "keypoints", items: [
          "`firebase_core` must be initialized once, before `runApp()`, before using any other Firebase product.",
          "`firebase_auth` covers email/password, phone, and social sign-in out of the box.",
          "Firestore's real-time `Stream`s pair naturally with `StreamBuilder` for live-updating UI.",
        ]},
      ],
    },

    // ---------------- PUSH NOTIFICATIONS ----------------
    {
      number: "x",
      title: "Push Notifications",
      blocks: [
        { type: "p", text: "Two complementary packages cover most notification needs: **`firebase_messaging`** for remote push notifications sent from a server/Firebase console, and **`flutter_local_notifications`** for notifications scheduled or triggered entirely on-device, without any backend involved." },
        { type: "h3", text: "Remote Push with Firebase Cloud Messaging" },
        { type: "code", text: [
          "import 'package:firebase_messaging/firebase_messaging.dart';",
          "",
          "Future<void> setupPushNotifications() async {",
          "  final messaging = FirebaseMessaging.instance;",
          "  await messaging.requestPermission();",
          "",
          "  final token = await messaging.getToken();",
          "  print('Device token: $token'); // send this to your backend",
          "",
          "  FirebaseMessaging.onMessage.listen((message) {",
          "    print('Notification received: ${message.notification?.title}');",
          "  });",
          "}",
        ].join("\n") },
        { type: "h3", text: "Local, On-Device Notifications" },
        { type: "code", text: [
          "import 'package:flutter_local_notifications/flutter_local_notifications.dart';",
          "",
          "final _notifications = FlutterLocalNotificationsPlugin();",
          "",
          "Future<void> showReminder() async {",
          "  const androidDetails = AndroidNotificationDetails(",
          "    'reports_channel', 'Report Reminders',",
          "    importance: Importance.high,",
          "  );",
          "  await _notifications.show(",
          "    0, 'Quarterly Report Due',",
          "    'Please submit your section before Friday.',",
          "    const NotificationDetails(android: androidDetails),",
          "  );",
          "}",
        ].join("\n") },
        { type: "keypoints", items: [
          "`firebase_messaging` handles server-sent push notifications; `flutter_local_notifications` handles on-device scheduling.",
          "Requesting notification permission explicitly (iOS especially) is required before notifications will be delivered.",
          "A device's FCM token identifies it for push targeting and should be sent to your backend once retrieved.",
        ]},
      ],
    },

    // ---------------- APP ICONS SPLASH FLAVORS ----------------
    {
      number: "x",
      title: "App Icons, Splash Screens & Build Flavors",
      blocks: [
        { type: "h3", text: "App Icons" },
        { type: "p", text: "The `flutter_launcher_icons` package generates every required icon resolution for both Android and iOS from a single source image." },
        { type: "code", text: [
          "# pubspec.yaml",
          "dev_dependencies:",
          "  flutter_launcher_icons: ^0.13.0",
          "",
          "flutter_launcher_icons:",
          "  android: true",
          "  ios: true",
          "  image_path: 'assets/icon/app_icon.png'",
        ].join("\n") },
        { type: "code", text: "flutter pub run flutter_launcher_icons" },
        { type: "h3", text: "Splash Screens" },
        { type: "p", text: "The `flutter_native_splash` package similarly generates the native splash screen shown while the Flutter engine initializes — before any Dart code, including `main()`, has run." },
        { type: "code", text: [
          "flutter_native_splash:",
          "  color: '#FFFFFF'",
          "  image: assets/icon/splash_logo.png",
        ].join("\n") },
        { type: "h3", text: "Build Flavors — dev / staging / production" },
        { type: "p", text: "Flavors let one codebase produce distinct app variants (different API endpoints, app names, or icons) for development, staging, and production — installed side-by-side on the same device without conflicting." },
        { type: "code", text: [
          "// lib/main_dev.dart",
          "void main() {",
          "  runApp(const MyApp(apiUrl: 'https://dev.api.example.com'));",
          "}",
          "",
          "// lib/main_prod.dart",
          "void main() {",
          "  runApp(const MyApp(apiUrl: 'https://api.example.com'));",
          "}",
        ].join("\n") },
        { type: "code", text: [
          "flutter run --target lib/main_dev.dart",
          "flutter build apk --target lib/main_prod.dart --release",
        ].join("\n") },
        { type: "keypoints", items: [
          "`flutter_launcher_icons` and `flutter_native_splash` automate two of the most tedious, error-prone manual asset tasks in mobile development.",
          "Build flavors let dev/staging/production variants of an app coexist and point at different backends without maintaining separate codebases.",
        ]},
      ],
    },

    // ---------------- ARCHITECTURE & DI ----------------
    {
      number: "x",
      title: "App Architecture & Dependency Injection",
      blocks: [
        { type: "p", text: "As a Flutter app grows past a handful of screens, mixing UI, business logic, and data-fetching directly inside widgets becomes hard to test and maintain. A layered architecture separates these concerns; **dependency injection** (DI) is the technique of supplying a class's dependencies from the outside rather than having it construct them itself, which is what makes each layer independently testable." },
        { type: "h3", text: "A Simple Repository Pattern" },
        { type: "code", text: [
          "// 1. Abstract contract — the UI and business logic depend on this, not a concrete implementation",
          "abstract class StudentRepository {",
          "  Future<List<Student>> getStudents();",
          "}",
          "",
          "// 2. A concrete implementation talking to a real API",
          "class ApiStudentRepository implements StudentRepository {",
          "  final http.Client client;",
          "  ApiStudentRepository(this.client);",
          "",
          "  @override",
          "  Future<List<Student>> getStudents() async {",
          "    final response = await client.get(Uri.parse('https://api.example.com/students'));",
          "    final list = jsonDecode(response.body) as List;",
          "    return list.map((j) => Student.fromJson(j)).toList();",
          "  }",
          "}",
          "",
          "// 3. A fake implementation — trivially swapped in for tests, no network needed",
          "class FakeStudentRepository implements StudentRepository {",
          "  @override",
          "  Future<List<Student>> getStudents() async =>",
          "      [Student(name: 'Test Student', rollNumber: 1)];",
          "}",
        ].join("\n") },
        { type: "h3", text: "Injecting the Dependency" },
        { type: "code", text: [
          "class StudentListScreen extends StatelessWidget {",
          "  final StudentRepository repository; // supplied from outside, not created here",
          "  const StudentListScreen({super.key, required this.repository});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return FutureBuilder<List<Student>>(",
          "      future: repository.getStudents(),",
          "      builder: (context, snapshot) {",
          "        // ... render based on snapshot, exactly as in Unit 21",
          "        return const SizedBox();",
          "      },",
          "    );",
          "  }",
          "}",
          "",
          "// Production: StudentListScreen(repository: ApiStudentRepository(http.Client()))",
          "// Testing:    StudentListScreen(repository: FakeStudentRepository())",
        ].join("\n") },
        { type: "note", kind: "tip", text: "For larger apps, packages like `get_it` (a simple service locator) or `riverpod` (which has DI built into its provider model) automate wiring dependencies together, but the underlying idea — depend on an abstraction, supply the concrete implementation from outside — stays the same." },
        { type: "table", header: ["Layer", "Responsibility"],
          rows: [
            ["Presentation (widgets)", "Display data and forward user actions — no business logic or direct API/database calls"],
            ["Domain / business logic", "Application rules, validation, orchestration — framework-agnostic where possible"],
            ["Data (repositories)", "Fetching and persisting data — the only layer that knows about the API, database, or cache"],
          ]},
        { type: "keypoints", items: [
          "Dependency injection means a class receives its dependencies from outside rather than constructing them itself.",
          "Coding against an abstract repository interface, not a concrete implementation, is what makes swapping in a fake/test version trivial.",
          "Separating presentation, domain, and data layers keeps a growing app testable and easier to reason about.",
        ]},
      ],
    },

    // ---------------- INTEGRATION TESTING ----------------
    {
      number: "x",
      title: "Integration Testing",
      blocks: [
        { type: "p", text: "Integration tests (via the `integration_test` package) run the **complete, real app** — not a simulated widget environment — on an actual device or emulator, driving it exactly the way a user would. They're slower than unit or widget tests but catch problems those levels cannot, such as issues specific to a real platform's rendering or plugin behaviour." },
        { type: "code", text: [
          "# pubspec.yaml",
          "dev_dependencies:",
          "  integration_test:",
          "    sdk: flutter",
        ].join("\n") },
        { type: "code", text: [
          "// integration_test/app_test.dart",
          "import 'package:flutter_test/flutter_test.dart';",
          "import 'package:integration_test/integration_test.dart';",
          "import 'package:my_app/main.dart' as app;",
          "",
          "void main() {",
          "  IntegrationTestWidgetsFlutterBinding.ensureInitialized();",
          "",
          "  testWidgets('full login flow', (tester) async {",
          "    app.main();",
          "    await tester.pumpAndSettle();",
          "",
          "    await tester.enterText(find.byKey(const Key('emailField')), 'test@lbrce.ac.in');",
          "    await tester.enterText(find.byKey(const Key('passwordField')), 'password123');",
          "    await tester.tap(find.byKey(const Key('loginButton')));",
          "    await tester.pumpAndSettle();",
          "",
          "    expect(find.text('Welcome'), findsOneWidget);",
          "  });",
          "}",
        ].join("\n") },
        { type: "code", text: "flutter test integration_test/app_test.dart" },
        { type: "note", kind: "tip", text: "`pumpAndSettle()` repeatedly pumps frames until no more are scheduled — ideal after actions that trigger animations or async work, so the test waits for the UI to fully finish reacting before making assertions." },
        { type: "keypoints", items: [
          "Integration tests exercise the real, compiled app on a device/emulator — the closest automated testing gets to actual user behaviour.",
          "`find.byKey(...)` is the most robust way to locate widgets in tests, since it doesn't depend on visible text that might change or be localized.",
          "`pumpAndSettle()` waits out animations and async work before assertions run.",
        ]},
      ],
    },

    // ---------------- PERFORMANCE ----------------
    {
      number: "x",
      title: "Performance Optimization & Best Practices",
      blocks: [
        { type: "p", text: "Flutter targets 60 (or 120, on capable devices) frames per second by default. Most performance problems come from rebuilding, laying out, or repainting more of the widget tree than actually changed." },
        { type: "h3", text: "Use const Constructors Wherever Possible" },
        { type: "code", text: [
          "// Rebuilt every time the parent rebuilds, even though nothing about it changes",
          "Text('Static Label')",
          "",
          "// Built once and reused — Flutter skips rebuilding it entirely",
          "const Text('Static Label')",
        ].join("\n") },
        { type: "h3", text: "Keep build() Methods Cheap" },
        { type: "ul", items: [
          "Never perform network calls, heavy computation, or file I/O directly inside `build()` — it can run many times per second during animations.",
          "Extract widgets that don't depend on frequently-changing state into their own `const` or separately-built classes, rather than rebuilding them as part of a large parent's `build()`.",
          "Prefer `ListView.builder`/`GridView.builder` over eagerly building every item up front for any list that could grow large (Unit 17).",
        ]},
        { type: "h3", text: "Scope Rebuilds Precisely" },
        { type: "code", text: [
          "// Rebuilds the ENTIRE subtree whenever CounterModel changes",
          "Consumer<CounterModel>(",
          "  builder: (context, model, child) => Column(",
          "    children: [",
          "      ExpensiveStaticHeader(), // gets needlessly rebuilt too",
          "      Text('${model.count}'),",
          "    ],",
          "  ),",
          ")",
          "",
          "// Better — the 'child' parameter is built once and passed through untouched",
          "Consumer<CounterModel>(",
          "  builder: (context, model, child) => Column(",
          "    children: [child!, Text('${model.count}')],",
          "  ),",
          "  child: const ExpensiveStaticHeader(),",
          ")",
        ].join("\n") },
        { type: "h3", text: "Diagnose, Don't Guess" },
        { type: "table", header: ["Tool", "Shows you"],
          rows: [
            ["DevTools Performance tab", "Frame render times; spot janky frames over 16ms (60fps) or 8ms (120fps)"],
            ["\"Repaint Rainbow\" (`debugRepaintRainbowEnabled`)", "Visually flashes any region that repaints, revealing unnecessary repaints at a glance"],
            ["Widget rebuild counts (DevTools)", "Which widgets rebuild far more often than expected"],
          ]},
        { type: "keypoints", items: [
          "`const` constructors let Flutter skip rebuilding widgets that provably haven't changed — use them by default wherever a widget's arguments are compile-time constants.",
          "Keep `build()` fast and side-effect-free; heavy work belongs in a repository/service layer, not inline in the widget tree.",
          "The `child` parameter pattern (seen in `AnimatedBuilder` and `Consumer`) lets you exclude a static subtree from rebuilding.",
          "Use DevTools to measure before optimizing — intuition about what's \"probably slow\" in Flutter is often wrong.",
        ]},
      ],
    },
  ],
};
