module.exports = {
  partTitle: "PART V — QUICK-REFERENCE APPENDICES",
  partSubtitle: "Look-up material for daily use once you know the concepts",
  units: [
    // ---------------- APPENDIX A ----------------
    {
      number: "A",
      title: "Dart Syntax Quick Reference",
      blocks: [
        { type: "table", header: ["Category", "Syntax"],
          rows: [
            ["Variable", "`var x = 10;`  ·  `final x = 10;`  ·  `const x = 10;`  ·  `int x = 10;`"],
            ["Nullable variable", "`String? name;`"],
            ["String interpolation", "`'Hello $name, total: ${a + b}'`"],
            ["If / else", "`if (cond) {...} else if (cond2) {...} else {...}`"],
            ["Ternary", "`cond ? valueIfTrue : valueIfFalse`"],
            ["Switch expression", "`var r = switch (x) { 1 => 'one', _ => 'other' };`"],
            ["for loop", "`for (int i = 0; i < n; i++) {...}`"],
            ["for-in loop", "`for (var item in list) {...}`"],
            ["while / do-while", "`while (cond) {...}`  ·  `do {...} while (cond);`"],
            ["Function", "`returnType name(params) { ... }`  or  `returnType name(params) => expr;`"],
            ["Optional positional param", "`void f(String a, [int? b]) {...}`"],
            ["Named params", "`void f({required String a, int b = 0}) {...}`"],
            ["Anonymous function", "`(a, b) => a + b`"],
            ["List", "`List<int> l = [1, 2, 3];`"],
            ["Set", "`Set<String> s = {'a', 'b'};`"],
            ["Map", "`Map<String, int> m = {'a': 1};`"],
            ["Spread operator", "`[...list1, ...list2]`"],
            ["Class", "`class Name { ... }`"],
            ["Constructor (shorthand)", "`Name(this.field1, this.field2);`"],
            ["Named constructor", "`Name.empty() : field = null;`"],
            ["Factory constructor", "`factory Name.fromJson(Map j) { ... }`"],
            ["Inheritance", "`class Sub extends Super { ... }`"],
            ["Interface adoption", "`class C implements SomeInterface { ... }`"],
            ["Mixin", "`class C with SomeMixin { ... }`"],
            ["Abstract class", "`abstract class Shape { double area(); }`"],
            ["Generic class", "`class Box<T> { T value; Box(this.value); }`"],
            ["Try/catch", "`try {...} on SomeError catch (e) {...} finally {...}`"],
            ["Throw", "`throw Exception('message');`"],
            ["Future / async", "`Future<T> f() async { return await other(); }`"],
            ["Stream", "`Stream<T> s() async* { yield value; }`"],
            ["Await for", "`await for (var v in stream) {...}`"],
            ["Null-aware access", "`obj?.member`  ·  `value ?? fallback`  ·  `value ??= fallback`  ·  `value!`"],
            ["late", "`late String token;`"],
            ["Import", "`import 'package:name/file.dart';`  ·  `import 'dart:core';`"],
          ]},
      ],
    },

    // ---------------- APPENDIX B ----------------
    {
      number: "B",
      title: "Flutter Widget Catalog (Quick Reference)",
      blocks: [
        { type: "h3", text: "Layout" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`Container`", "`padding, margin, decoration, color, width, height, alignment`", "General-purpose box"],
            ["`Row` / `Column`", "`mainAxisAlignment, crossAxisAlignment, children`", "Horizontal / vertical layout"],
            ["`Stack`", "`alignment, children`", "Overlap widgets"],
            ["`Positioned`", "`top, bottom, left, right`", "Position a child inside a `Stack`"],
            ["`Expanded`", "`flex, child`", "Fill remaining space in Row/Column"],
            ["`Flexible`", "`flex, fit, child`", "Allow a child to shrink/grow flexibly"],
            ["`Padding`", "`padding, child`", "Add space around a child"],
            ["`Center`", "`child`", "Center a single child"],
            ["`Align`", "`alignment, child`", "Position a child within available space"],
            ["`SizedBox`", "`width, height, child`", "Fixed size box / spacer"],
            ["`Wrap`", "`spacing, runSpacing, children`", "Flowing multi-line layout"],
          ]},
        { type: "h3", text: "Scrolling" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`ListView.builder`", "`itemCount, itemBuilder`", "Efficient scrollable list"],
            ["`GridView.builder`", "`gridDelegate, itemCount, itemBuilder`", "Scrollable grid"],
            ["`SingleChildScrollView`", "`scrollDirection, child`", "Make one overflowing child scrollable"],
          ]},
        { type: "h3", text: "Text & Media" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`Text`", "`style, textAlign, overflow, maxLines`", "Display a string"],
            ["`Image.asset` / `.network`", "`fit, width, height`", "Display an image"],
            ["`Icon`", "`icon, size, color`", "Display a Material icon"],
          ]},
        { type: "h3", text: "Input" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`ElevatedButton`", "`onPressed, child, style`", "Primary action button"],
            ["`TextButton` / `OutlinedButton`", "`onPressed, child`", "Secondary action button"],
            ["`TextField` / `TextFormField`", "`controller, decoration, onChanged, validator`", "Text input"],
            ["`Checkbox` / `Switch` / `Radio`", "`value, onChanged`", "Boolean / choice input"],
            ["`DropdownButton`", "`value, items, onChanged`", "Select from a list"],
          ]},
        { type: "h3", text: "Structure & Navigation" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`MaterialApp`", "`title, theme, home, routes`", "Root app configuration"],
            ["`Scaffold`", "`appBar, body, floatingActionButton, drawer, bottomNavigationBar`", "Standard screen structure"],
            ["`AppBar`", "`title, actions, leading`", "Top app bar"],
            ["`Drawer`", "`child`", "Slide-out side menu"],
            ["`BottomNavigationBar`", "`items, currentIndex, onTap`", "Bottom tab navigation"],
          ]},
        { type: "h3", text: "Async & State" },
        { type: "table", header: ["Widget", "Key Properties", "Use"],
          rows: [
            ["`FutureBuilder`", "`future, builder`", "Render UI based on a `Future`'s state"],
            ["`StreamBuilder`", "`stream, builder`", "Render UI based on a `Stream`'s latest value"],
            ["`ChangeNotifierProvider`", "`create, child`", "Provide a `ChangeNotifier` to descendants"],
          ]},
      ],
    },

    // ---------------- APPENDIX C ----------------
    {
      number: "C",
      title: "Common Errors & Troubleshooting",
      blocks: [
        { type: "table", header: ["Error / Symptom", "Likely Cause", "Fix"],
          rows: [
            ["`RenderFlex overflowed by N pixels`", "A `Row`/`Column`'s children need more space than is available", "Wrap the offending child in `Expanded`/`Flexible`, or make the parent scrollable"],
            ["`setState() called after dispose()`", "An async callback (timer, network response) fired after the widget was removed from the tree", "Check `if (mounted)` before calling `setState()` inside async callbacks"],
            ["`type 'Null' is not a subtype of type 'X'`", "A nullable value was used where a non-null value was expected", "Add a null check, use `??`, or fix the source of the null value"],
            ["`The method 'X' was called on null`", "Pre–null-safety style bug — accessing a member on a null object", "Ensure null safety is enabled (default since Dart 2.12) and check nullability"],
            ["\"Hot reload\" doesn't reflect a change", "Change affects `main()`, global/static state, or an enum — these require a full restart", "Perform a hot **restart** (`R`) instead of hot reload"],
            ["`No MaterialLocalizations found`", "A Material widget (e.g. `Text`, `Tooltip`) was used above/outside a `MaterialApp`", "Ensure the widget is inside `MaterialApp`'s widget tree"],
            ["`Vertical viewport was given unbounded height`", "A `ListView`/`Column` of unknown height was placed inside another unbounded-height parent", "Give the parent a fixed height, or wrap the list in `Expanded`/`SizedBox`"],
            ["`Duplicate GlobalKey detected`", "The same `GlobalKey` was assigned to more than one widget", "Ensure each `GlobalKey` is unique, typically one per stateful form/widget instance"],
            ["Gradle build fails after adding a plugin", "Android Gradle/Kotlin/plugin version mismatch", "Run `flutter clean`, then `flutter pub get`, and check the plugin's required Android Gradle Plugin version"],
            ["App builds but assets don't show", "Asset not declared in `pubspec.yaml`, or a typo in the path", "Double-check indentation and paths under `flutter: assets:` and re-run `flutter pub get`"],
          ]},
        { type: "note", kind: "tip", text: "`flutter clean` followed by `flutter pub get` resolves a surprising number of \"it worked yesterday\" build issues by clearing stale cached build artifacts." },
      ],
    },

    // ---------------- APPENDIX D ----------------
    {
      number: "D",
      title: "Essential Packages Directory",
      blocks: [
        { type: "table", header: ["Package", "Purpose"],
          rows: [
            ["`http`", "Simple REST API calls"],
            ["`dio`", "Advanced HTTP client — interceptors, form data, progress tracking"],
            ["`provider`", "Recommended entry-level state management"],
            ["`flutter_riverpod`", "Compile-safe, testable state management (Provider's successor)"],
            ["`flutter_bloc`", "Event-driven state management for larger apps"],
            ["`go_router`", "Declarative, URL-based navigation and deep linking"],
            ["`shared_preferences`", "Simple key-value local storage"],
            ["`sqflite`", "Local SQL database"],
            ["`hive` / `hive_flutter`", "Fast local NoSQL storage"],
            ["`json_serializable` + `json_annotation`", "Auto-generate `fromJson`/`toJson` boilerplate"],
            ["`intl`", "Date, number, and currency formatting; localization"],
            ["`image_picker`", "Pick images/videos from camera or gallery"],
            ["`cached_network_image`", "Network images with automatic caching and placeholders"],
            ["`flutter_svg`", "Render SVG vector graphics"],
            ["`url_launcher`", "Open URLs, email, phone dialer from within the app"],
            ["`permission_handler`", "Request and check runtime device permissions"],
            ["`firebase_core` + `cloud_firestore`", "Firebase backend integration"],
            ["`flutter_local_notifications`", "Schedule and display local notifications"],
            ["`lottie`", "Render Lottie/After Effects animations"],
            ["`flutter_test` (built-in)", "Unit and widget testing"],
          ]},
        { type: "note", kind: "tip", text: "Always check a package's pub.dev score, last-published date, and \"platform support\" table before adopting it — an unmaintained or narrowly-supported package is one of the most common sources of hard-to-fix build issues months later." },
      ],
    },

    // ---------------- APPENDIX E ----------------
    {
      number: "E",
      title: "Command-Line Reference",
      blocks: [
        { type: "h3", text: "Flutter CLI" },
        { type: "table", header: ["Command", "Purpose"],
          rows: [
            ["`flutter doctor`", "Diagnose the development environment setup"],
            ["`flutter create <name>`", "Scaffold a new project"],
            ["`flutter run`", "Build and run on a connected device/emulator (debug mode)"],
            ["`flutter run --release`", "Run an optimized release build"],
            ["`flutter pub get`", "Fetch dependencies declared in `pubspec.yaml`"],
            ["`flutter pub upgrade`", "Upgrade dependencies within their allowed version ranges"],
            ["`flutter pub outdated`", "Show which dependencies have newer versions available"],
            ["`flutter clean`", "Remove build artifacts — useful when a build behaves unexpectedly"],
            ["`flutter build apk` / `appbundle`", "Build an Android release artifact"],
            ["`flutter build ios`", "Build an iOS release artifact (requires Xcode/macOS)"],
            ["`flutter build web`", "Build a web release bundle"],
            ["`flutter test`", "Run unit and widget tests"],
            ["`flutter analyze`", "Run the static analyzer across the project"],
            ["`flutter devices`", "List connected devices and running emulators"],
            ["`flutter logs`", "Stream logs from a running app"],
            ["`flutter gen-l10n`", "Regenerate localization classes from `.arb` files"],
          ]},
        { type: "h3", text: "Dart CLI" },
        { type: "table", header: ["Command", "Purpose"],
          rows: [
            ["`dart --version`", "Show the installed Dart SDK version"],
            ["`dart run <file>.dart`", "Run a standalone Dart script"],
            ["`dart format .`", "Auto-format every Dart file in the current directory"],
            ["`dart analyze`", "Run the static analyzer"],
            ["`dart fix --apply`", "Automatically apply suggested lint fixes"],
            ["`dart pub add <package>`", "Add a dependency to `pubspec.yaml` and fetch it"],
            ["`dart compile exe <file>.dart`", "Compile a standalone Dart script to a native executable"],
          ]},
      ],
    },

    // ---------------- APPENDIX F ----------------
    {
      number: "F",
      title: "DevTools & Keyboard Shortcuts",
      blocks: [
        { type: "h3", text: "Terminal Shortcuts While flutter run Is Active" },
        { type: "table", header: ["Key", "Action"],
          rows: [
            ["`r`", "Hot reload"],
            ["`R`", "Hot restart"],
            ["`p`", "Toggle the debug paint / layout guideline overlay"],
            ["`o`", "Toggle the platform (Android/iOS) look-and-feel for testing"],
            ["`w`", "Dump the widget tree to the console"],
            ["`d`", "Detach (leave the app running, exit the debug session)"],
            ["`q`", "Quit the running app"],
          ]},
        { type: "h3", text: "Flutter DevTools Panels" },
        { type: "table", header: ["Panel", "Use it to"],
          rows: [
            ["Flutter Inspector", "Visually browse the widget tree, select widgets on-screen, inspect their properties"],
            ["Performance", "Find janky frames, see frame render timings"],
            ["CPU Profiler", "Profile where CPU time is being spent in Dart code"],
            ["Memory", "Track memory usage over time, spot leaks (e.g. undisposed controllers)"],
            ["Network", "Inspect HTTP requests and responses made by the app"],
            ["Logging", "View structured log output from the running app"],
          ]},
        { type: "note", kind: "tip", text: "DevTools opens automatically in your IDE (VS Code/Android Studio show a button) or via the URL printed to the terminal when you run `flutter run` — no separate installation needed for a typical setup." },
      ],
    },

    // ---------------- APPENDIX G ----------------
    {
      number: "G",
      title: "Glossary of Terms",
      blocks: [
        { type: "table", header: ["Term", "Meaning"],
          rows: [
            ["Widget", "An immutable description of a piece of UI"],
            ["State", "Mutable data associated with a `StatefulWidget`, held in a separate `State` object"],
            ["BuildContext", "A handle to a widget's location in the widget tree, used to look up inherited data"],
            ["Hot reload", "Injecting updated code into a running app without losing state"],
            ["Hot restart", "Restarting the app from scratch, resetting all state, faster than a full stop/run"],
            ["Widget tree", "The declarative hierarchy of widgets describing the UI"],
            ["Element tree", "The live, mutable instantiation of the widget tree managing lifecycle"],
            ["RenderObject", "The layer responsible for layout, painting, and hit-testing"],
            ["Future", "A value (or error) that will be available once, at some point in the future"],
            ["Stream", "A sequence of asynchronous values delivered over time"],
            ["Mixin", "Reusable functionality that can be \"mixed in\" to otherwise unrelated classes via `with`"],
            ["Null safety", "Compile-time guarantee that non-nullable variables can never hold `null`"],
            ["pubspec.yaml", "The manifest file declaring a project's dependencies, assets, and metadata"],
            ["Scaffold", "A widget providing the standard visual structure of a screen (app bar, body, drawer, etc.)"],
            ["ChangeNotifier", "A class that can notify listeners when its internal data changes, the basis of `Provider`"],
            ["Ticker / vsync", "Mechanism synchronizing animations with the device's screen refresh rate"],
            ["AOT / JIT compilation", "Ahead-of-time (release, optimized) vs Just-in-time (development, supports hot reload) compilation"],
          ]},
      ],
    },

    // ---------------- APPENDIX H ----------------
    {
      number: "H",
      title: "Practice & Viva Questions",
      blocks: [
        { type: "p", text: "Short-answer questions organized by part, suitable for self-assessment, tutorial sheets, or viva-voce preparation. Answers can be located in the corresponding unit referenced." },
        { type: "h3", text: "Part I — Dart Language" },
        { type: "ol", items: [
          "What is the difference between `final` and `const`? Give an example where only `final` would work. (Unit 2)",
          "Why does Dart use `~/` instead of a truncating `/` for integer division? (Unit 2)",
          "What is the difference between a classic `switch` statement and a Dart 3 switch *expression*? (Unit 3)",
          "Explain the difference between optional positional parameters (`[...]`) and named parameters (`{...}`). (Unit 4)",
          "What does it mean for a function to be a \"closure\"? Give an example. (Unit 4)",
          "Compare `List`, `Set`, and `Map` in terms of ordering and duplicate handling. (Unit 5)",
          "Why does Dart not need a separate `interface` keyword? (Unit 6)",
          "What is a mixin, and how is it different from inheritance via `extends`? (Unit 6)",
          "Why are generics preferable to using `dynamic` for a container class? (Unit 7)",
          "What is the difference between `on ExceptionType catch (e)` and a bare `catch (e)`? (Unit 8)",
          "Explain the difference between `Future` and `Stream` with one real-world example of each. (Unit 9)",
          "What problem does sound null safety solve, and what does the `!` operator actually do at runtime? (Unit 10)",
          "What is the purpose of `pubspec.yaml`, and what does the caret (`^`) mean in a version constraint? (Unit 11)",
        ]},
        { type: "h3", text: "Part II — Flutter Framework" },
        { type: "ol", items: [
          "Explain the relationship between the widget tree, element tree, and render tree. (Unit 12)",
          "What is the difference between `StatelessWidget` and `StatefulWidget`? When would you choose one over the other? (Unit 15)",
          "Why is calling `setState()` necessary — what would happen if you simply mutated a state field directly? (Unit 15)",
          "What is the purpose of `Expanded` and `Flexible` inside a `Row`/`Column`? (Unit 17)",
          "Why should `ListView.builder` be preferred over `ListView(children: [...])` for long lists? (Unit 17)",
          "Describe the flow of data when using `Navigator.push` with `await` and a `Navigator.pop(context, result)` on the pushed screen. (Unit 19)",
          "What problem does `Provider`/`ChangeNotifier` solve that `setState()` alone cannot? (Unit 20)",
          "Explain the difference between `context.watch<T>()` and `context.read<T>()`. (Unit 20)",
          "Why is a `fromJson` factory constructor a better practice than passing raw `Map<String, dynamic>` objects around an app? (Unit 21)",
          "When would you choose `sqflite` over `shared_preferences`? (Unit 22)",
          "What is the difference between an implicit animation (e.g. `AnimatedContainer`) and an explicit one using `AnimationController`? (Unit 23)",
          "Why must an `AnimationController` be disposed, and where should that happen? (Unit 23)",
          "What is the difference between a unit test, a widget test, and an integration test? (Unit 26)",
          "What is the difference between debug, profile, and release build modes, and when should each be used? (Unit 27)",
        ]},
        { type: "h3", text: "Advanced Topics & Capstone" },
        { type: "ol", items: [
          "How do records improve on returning multiple values from a function compared to pre-Dart-3 approaches?",
          "Why can't a `BuildContext` or an open database connection be passed into a Dart isolate?",
          "What problem does the repository pattern solve, and how does it make unit testing easier?",
          "In the capstone project, what would need to change to replace local `sqflite` storage with a remote REST API? What would *not* need to change, and why?",
          "Why does the capstone's `DetailsScreen` check `context.mounted` after awaiting a dialog result?",
        ]},
      ],
    },

    // ---------------- APPENDIX I ----------------
    {
      number: "I",
      title: "Suggested Practice Projects",
      blocks: [
        { type: "p", text: "Small, scoped projects to build after working through this manual, roughly ordered by difficulty. Each references the units most relevant to completing it." },
        { type: "table", header: ["Project", "Difficulty", "Key Units Exercised"],
          rows: [
            ["Unit converter (temperature, length, currency)", "Beginner", "Units 2–4, 15, 18"],
            ["Flashcard app for exam revision with a local question bank", "Beginner", "Units 5, 15–18, 22"],
            ["To-do list with categories and local persistence", "Beginner–Intermediate", "Units 15–20, 22"],
            ["Weather app calling a public REST API", "Intermediate", "Units 9, 21, and the Networking unit's `FutureBuilder` pattern"],
            ["Student attendance tracker with charts by subject", "Intermediate", "Units 20–22, plus a charting package from Appendix D"],
            ["Departmental event announcement app with Firebase backend", "Intermediate–Advanced", "The Firebase unit, Unit 19 (Navigation), Unit 20 (state)"],
            ["Multi-user chat app with WebSockets", "Advanced", "The WebSockets unit, Unit 20, Unit 9 (Streams)"],
            ["Full offline-first notes app with sync-when-online", "Advanced", "Units 21–22, the Architecture & DI unit, the Capstone pattern throughout"],
          ]},
        { type: "note", kind: "tip", text: "For classroom or lab use, the capstone project in Part IV can itself be assigned as a template: ask students to substitute a different domain (library book tracker, lab equipment log, event registration) while keeping the same layered architecture, forms, and persistence pattern." },
      ],
    },
  ],
};
